added burrow wheeler transformation algorithm in all four languages
Kumar-laxmi/Algorithms pull request #1067
Opened 2023-06-06 09:45 UTC by VoidVampire

## 🛠️ Issue (Number)

Issue no [#834](https://github.com/Kumar-laxmi/Algorithms/issues/834)

## 👨‍💻 Changes proposed
Additon of Burrow Wheeler Transform algorithm in C, C++, Java, Python

## ✔️ Check List (Check all the applicable boxes) 

- [X] My code follows the code style of this project.
- [X] This PR does not contain plagiarized content.
- [X] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers

## 📷 Screenshots
### C++
![bwt_cpp](https://github.com/Kumar-laxmi/Algorithms/assets/80760499/9b6a85ac-bc85-4bbb-838b-d399c0ba68a3)

### Java
![bwt_java](https://github.com/Kumar-laxmi/Algorithms/assets/80760499/24a35f81-3c89-4247-bfea-940298582a04)

### Python
![bwt_python](https://github.com/Kumar-laxmi/Algorithms/assets/80760499/46e63462-d46a-430b-9790-f0281a0668ca)

### C
![bwt_c](https://github.com/Kumar-laxmi/Algorithms/assets/80760499/5ffa9268-4559-4e1c-bd86-f26948b13a69)

2023-06-07 05:28 UTC, VoidVampire commented
Was I not supposed to update README.md?

2023-06-07 05:39 UTC, zugzwang03 requested changes
resolve the conflicts

2023-06-07 12:37 UTC, VoidVampire commented
This is the first time I am using git and contributing and i tried to resolve merge conflicts but somehow, I have closed the PR :'(

2023-06-08 04:27 UTC, 072arushi approved these changes

2023-06-08 06:05 UTC, zugzwang03 approved these changes

2023-06-08 18:22 UTC, Arun9739 approved these changes

2023-06-09 02:56 UTC, Kumar-laxmi approved these changes

2023-06-09 02:57 UTC, merged