Grey Wolf Optimization Added
Kumar-laxmi/Algorithms pull request #1070
Opened 2023-06-06 11:28 UTC by rayarka26

Issue Number 1008

## 🛠️ Issue (Number)

Issue no #

## 👨‍💻 Changes proposed

## ✔️ Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers

## 📷 Screenshots

2023-06-06 11:32 UTC, rayarka26 commented
The Correct output for a particular objective function screenshot is attached
It contains C, C++ and Python Codes
![Screenshot (66)](https://github.com/Kumar-laxmi/Algorithms/assets/74251803/51de26d9-c1f8-40e7-9772-0bbe8dd00d48)

2023-06-08 04:27 UTC, 072arushi approved these changes

2023-06-08 04:27 UTC, 072arushi approved these changes

2023-06-08 18:08 UTC, Arun9739 approved these changes

2023-06-09 02:04 UTC, Kumar-laxmi requested changes
Please add the JAVA Program file

2023-06-09 02:04 UTC, Kumar-laxmi commented on Python/Optimization/tempCodeRunnerFile.py
> +
Remove this file

2023-06-09 02:44 UTC, rayarka26 commented
@Kumar-laxmi java code has been uploaded and all changes done.
Output remains same

2023-06-09 13:16 UTC, Kumar-laxmi requested changes
Place all java class codes in one file

2023-06-09 17:34 UTC, rayarka26 commented
@Kumar-laxmi done please check

2023-06-09 17:40 UTC, rayarka26 commented
@Kumar-laxmi i also wanted to contribute one more algorithm  as issue number #958 , which you missed please check once

2023-06-11 01:11 UTC, Kumar-laxmi approved these changes

2023-06-11 01:12 UTC, merged