added-chinese-rem
Kumar-laxmi/Algorithms pull request #1127
Opened 2023-06-08 08:10 UTC by kritika2313

## 🛠️ Issue (Number)

Issue no #1035 

## 👨‍💻 Changes proposed

added chinese remainder  theorem in c,c++,java and python

## ✔️ Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers

## 📷 Screenshots

2023-06-08 09:57 UTC, Kumar-laxmi commented
@kritika2313 Please add the screen shot of the output

2023-06-08 18:15 UTC, Arun9739 requested changes
@kritika2313 Take input from user in the program

2023-06-09 11:26 UTC, kritika2313 commented
i have made the changes pls have a look.

2023-06-09 14:31 UTC, zugzwang03 approved these changes

2023-06-10 07:55 UTC, Arun9739 approved these changes

2023-06-11 01:03 UTC, Kumar-laxmi approved these changes

2023-06-11 01:04 UTC, merged