Added Hill climbing algorithm
Kumar-laxmi/Algorithms pull request #1138
Opened 2023-06-08 12:05 UTC by sha0urya

Added Hill climbing algorithm in C, C++, Java, Python.

Also Updated README.md file.

## 🛠️ Issue (Number)

Issue no #680 

## 👨‍💻 Changes proposed

Hill climbing is a simple optimization algorithm used to find the best solution in a search space. It is inspired by the metaphor of climbing a hill to reach the highest point.

The algorithm starts with an initial solution and iteratively makes small incremental changes to it, always moving in the direction of improvement.

Will add Hill climbing optimization algorithm with adequate comments for readers to get a clear understanding.
To add in C, C++, Java and Python.

## ✔️ Check List (Check all the applicable boxes) 

- [✔️] My code follows the code style of this project.
- [✔️] This PR does not contain plagiarized content.
- [✔️] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers

## 📷 Screenshots

![1686388429905~2](https://github.com/Kumar-laxmi/Algorithms/assets/94980644/b1034a02-0e67-4efa-ada9-f428838af2df)
![1686388605006~2](https://github.com/Kumar-laxmi/Algorithms/assets/94980644/fec5a97a-94d2-4590-b9a4-be842e36c2aa)
![1686388763466~2](https://github.com/Kumar-laxmi/Algorithms/assets/94980644/276c0f46-16e3-41c3-9b17-07aea60f13db)
![1686388316862~2](https://github.com/Kumar-laxmi/Algorithms/assets/94980644/76989eec-574e-467b-a419-efb9d363656e)

C++ Output 

![WhatsApp Image 2023-06-11 at 18 48 06](https://github.com/Kumar-laxmi/Algorithms/assets/94980644/7480a9d4-4331-4dcc-aed9-40df4c63e34a)

C Output 

![WhatsApp Image 2023-06-11 at 18 48 07](https://github.com/Kumar-laxmi/Algorithms/assets/94980644/40e3e4f3-8510-4984-8149-792e5d3ecd89)

Python Output

![WhatsApp Image 2023-06-11 at 18 48 07](https://github.com/Kumar-laxmi/Algorithms/assets/94980644/44099a5a-1a10-40df-b5c5-a8328b3019ef)

Java Output

![WhatsApp Image 2023-06-11 at 18 48 08](https://github.com/Kumar-laxmi/Algorithms/assets/94980644/06740485-6c8b-43a6-b0c4-bc6ffd637b94)

2023-06-08 13:26 UTC, Kumar-laxmi requested changes

2023-06-09 14:35 UTC, zugzwang03 approved these changes

2023-06-10 05:40 UTC, 072arushi requested changes
Add screenshots and complete the description

2023-06-11 06:34 UTC, Arun9739 requested changes
@sha0urya Add output screenshots

2023-06-11 17:09 UTC, 072arushi approved these changes

2023-06-13 08:37 UTC, Arun9739 approved these changes

2023-06-17 05:52 UTC, zugzwang03 approved these changes

2023-06-18 15:02 UTC, Kumar-laxmi approved these changes

2023-06-18 15:03 UTC, merged