[SSoC 2.0] Hierholzer Algorithm Completed !
Kumar-laxmi/Algorithms pull request #1143
Opened 2023-06-08 13:38 UTC by Avdhesh-Varshney

## 🛠️ Issue #1045 

Issue no #1045 

## 👨‍💻 Changes proposed

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers

## 📷 Screenshots
![Screenshot 2023-06-08 185409](https://github.com/Kumar-laxmi/Algorithms/assets/114330097/63425359-c9de-45d8-b38e-b7c484476b02)

2023-06-10 05:38 UTC, 072arushi approved these changes

2023-06-11 05:11 UTC, zugzwang03 approved these changes

2023-06-13 08:19 UTC, Arun9739 requested changes
@Avdhesh-Varshney Take input from user

2023-06-13 09:34 UTC, Avdhesh-Varshney commented
@Arun9739 @Kumar-laxmi  Sir, please review my pull request and merge it into the main branch for a successful contribution under SSoC 2.0 program

2023-06-14 15:43 UTC, Arun9739 approved these changes

2023-06-15 05:02 UTC, Avdhesh-Varshney commented
@Kumar-laxmi please merge this pull request for a successful contribution under SSoC 2.0

And requested to assign the issues #1043, #1044, #1052 and #1053
I have done with #1043, #1044 and #1052 and want to create a pull request under SSoC 2.0 program

2023-06-15 10:21 UTC, Kumar-laxmi approved these changes

2023-06-15 10:23 UTC, merged