Added Strong Number Codes
Kumar-laxmi/Algorithms pull request #1148
Opened 2023-06-08 15:25 UTC by HardikGoyal2003

Closes #1121

## 🛠️ Issue (1121)
Find whether the given number is strong number or not

Issue no #1121

## 👨‍💻 Changes proposed
To Add Code 
\
## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers

## 📷 Screenshots

2023-06-09 01:04 UTC, Kumar-laxmi requested changes
Add Java's program file and screen shots of output

2023-06-09 13:33 UTC, HardikGoyal2003 commented
> Add Java's program file and screen shots of output

@Kumar-laxmi Done!!! Thanks for opportunity..

2023-06-10 05:33 UTC, 072arushi approved these changes

2023-06-11 05:12 UTC, zugzwang03 approved these changes

2023-06-13 05:34 UTC, Kumar-laxmi commented
@Arun9739 Kindly review this PR

2023-06-14 15:41 UTC, Arun9739 approved these changes

2023-06-15 05:19 UTC, Kumar-laxmi approved these changes

2023-06-15 05:20 UTC, merged