rabin karp pattern matching algo in cpp
Kumar-laxmi/Algorithms pull request #117
Opened 2023-01-03 02:33 UTC by vijay-kumar-yadav

## 🛠️ Issue (Number)

Closes #96 

## 👨‍💻 Changes proposed

## ✔️ Check List (Check all the applicable boxes) 

- [ ✔️ ] My code follows the code style of this project.
- [✔️  ] This PR does not contain plagiarized content.
- [✔️  ] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers

Apology for previous conduct I didn't know I have kept code from gfg as I have learnt this algo from gfg dsa course also I had written the code earlier when I was learning that too 1yr ago.

## 📷 Screenshots
![image](https://user-images.githubusercontent.com/83089894/210293268-8f8ab9a5-1421-45d1-8236-8dd9ab27e2d7.png)

2023-01-03 06:32 UTC, Kumar-laxmi requested changes

2023-01-03 06:32 UTC, Kumar-laxmi commented on README.md
> +| 21.  | Rabin Karp | [C++](https://github.com/Kumar-laxmi/Algorithms/blob/main/C%2B%2B/Pattern-Matching/rabin_karp.cpp) | Pattern Matching |
Put Rabin Karp between index 8 & 9

2023-01-03 06:32 UTC, Kumar-laxmi commented on .vscode/settings.json
> +{
please remove folder '.vscode'

2023-01-03 06:33 UTC, vijay-kumar-yadav commented on .vscode/settings.json
> +{
ok

2023-01-03 06:35 UTC, vijay-kumar-yadav commented on README.md
> +| 21.  | Rabin Karp | [C++](https://github.com/Kumar-laxmi/Algorithms/blob/main/C%2B%2B/Pattern-Matching/rabin_karp.cpp) | Pattern Matching |
ok

2023-01-03 06:42 UTC, Kumar-laxmi commented
@vijay-kumar-yadav Is it ready to merge?

2023-01-03 06:56 UTC, vijay-kumar-yadav commented
> @vijay-kumar-yadav Is it ready to merge?
yes it is

2023-01-03 07:19 UTC, vijay-kumar-yadav commented
> @vijay-kumar-yadav Is it ready to merge?

yes

2023-01-04 04:53 UTC, Kumar-laxmi commented
@vijay-kumar-yadav Please resolve the **MERGE CONFLICT**

2023-01-04 05:54 UTC, vijay-kumar-yadav commented
> @vijay-kumar-yadav Please resolve the **MERGE CONFLICT**

I have to open new pr then it will be fixed

2023-01-04 05:54 UTC, closed without merging