Added catalan number programs
Kumar-laxmi/Algorithms pull request #1191
Opened 2023-06-09 13:39 UTC by KOMNOOB

## 🛠️ Issue (Number)

Issue no #1166 

## 👨‍💻 Changes proposed

## Changes
Problem Statement: Catalan Number

Problem Description:
The Catalan numbers form a sequence of natural numbers that occur in various counting problems, often involving recursive structures.
Given an integer n, your task is to find the nth Catalan number using dynamic programming/recursion.

Write a function Catalan(n) that takes in an integer n and returns the nth Catalan number.
I wrote those 2 algorithms in all languages.
## 📄 Note to reviewers
The folder named Dynamic-Programming under Java was causing errors locally in my machine due to which I can't run any program under that folder. So I changed its name to "Dynamic_Programming" and it worked.

## 📷 Screenshots
Java
![image](https://github.com/Kumar-laxmi/Algorithms/assets/92045934/4b42b606-353c-4bc3-a4ea-e97c49b3006a)

C++
![image](https://github.com/Kumar-laxmi/Algorithms/assets/92045934/0f7b7690-257c-412e-8658-e81503303f87)

Python
![image](https://github.com/Kumar-laxmi/Algorithms/assets/92045934/98beaa67-8678-46cf-b37d-a16211391972)

2023-06-09 13:57 UTC, Kumar-laxmi requested changes
Except Catalan Number's program files remove all other program files from this PR

2023-06-10 05:04 UTC, KOMNOOB commented
How to remove all other files ?

2023-06-11 05:09 UTC, zugzwang03 approved these changes

2023-06-11 17:08 UTC, 072arushi approved these changes

2023-06-13 08:34 UTC, Arun9739 approved these changes

2023-06-19 12:51 UTC, KOMNOOB commented
@Kumar-laxmi Will you merge this?

2023-12-29 13:52 UTC, closed without merging