Added Strong password problem using python
Kumar-laxmi/Algorithms pull request #12
Opened 2022-10-23 12:08 UTC by Sulagna-Dutta-Roy

Issue no: #10

2022-10-23 13:02 UTC, Kumar-laxmi commented
@Sulagna-Dutta-Roy Add all 4 files in one PR

2022-10-23 14:13 UTC, Sulagna-Dutta-Roy commented
Actually I wanted to make this pr only on python. But forget to mention in issue

2022-10-23 14:30 UTC, Kumar-laxmi commented
@Sulagna-Dutta-Roy  Just give it a try in other languages too

2022-10-23 14:40 UTC, Sulagna-Dutta-Roy commented
Sure 😄

2022-10-25 13:31 UTC, Kumar-laxmi commented
@Sulagna-Dutta-Roy Any progress?

2022-10-25 13:56 UTC, Kumar-laxmi requested changes

2022-10-25 13:56 UTC, Kumar-laxmi commented on Python/Cryptography/Strong Password.py
> +    if any(list(map(lambda x: x in nums,password))):
Please add the purpose of each if-statement

2022-10-25 13:56 UTC, Kumar-laxmi commented on Python/Cryptography/Strong Password.py
> +    if any(list(map(lambda x: x in nums,password))):
Explain each and every case OR edge condition that the if-statements are dealing

2022-10-30 20:28 UTC, closed without merging