Added code for Binary to Gray Conversion  and vice-versa in C,C++,Python and Java
Kumar-laxmi/Algorithms pull request #1224
Opened 2023-06-10 20:18 UTC by AK3847

Issue no #875

## 👨‍💻 Changes proposed

-  Added Code for Binary to Gray conversion and vice-versa in all 4 languages: C,C++,Java and Python

## ✔️ Check List (Check all the applicable boxes) 

- [✅] My code follows the code style of this project.
- [✅] This PR does not contain plagiarized content.
- [✅] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers

## 📷 Screenshots

- Output for C++ code:
 
![image](https://github.com/Kumar-laxmi/Algorithms/assets/94222544/0ef4e29c-17fb-4bf7-81f4-c9aebe2885f0)

- Output for C code:
![image](https://github.com/Kumar-laxmi/Algorithms/assets/94222544/20e60667-2552-43f6-b923-0680e9164d20)

- Output for Python code:
![image](https://github.com/Kumar-laxmi/Algorithms/assets/94222544/61aa731d-4525-4fcb-baaa-8a2e5bcddebf)

- Output for Java code:
![image](https://github.com/Kumar-laxmi/Algorithms/assets/94222544/89d13b15-9287-4ea0-b5e0-53e406ea5d04)

2023-06-11 01:07 UTC, Kumar-laxmi requested changes
Please place the program files in ```Binary``` folder

2023-06-11 05:10 UTC, zugzwang03 approved these changes

2023-06-11 06:56 UTC, AK3847 commented
@Kumar-laxmi I have modified the file locations as you requested please review it once.

2023-06-11 17:04 UTC, 072arushi approved these changes

2023-06-13 08:27 UTC, Arun9739 approved these changes

2023-06-15 15:20 UTC, Kumar-laxmi approved these changes

2023-06-16 01:14 UTC, merged