Add : Aho-Corasick Algorithm for Pattern Searching
Kumar-laxmi/Algorithms pull request #1244
Opened 2023-06-11 16:07 UTC by Aarsh30

## 🛠️ Issue (#928)

Issue no  #928
👨‍💻 Changes proposed
This pull request proposes improvements to the Aho-Corasick algorithm implementation inC, C++,Java and Python, focusing on:
Refactoring the code for better readability and performance.
Streamlining the update of residual capacities and flow.
Implementing best practices, such as code formatting and documentation.
Handling edge cases, like zero capacity edges and valid source/sink vertices.
These changes aim to enhance the algorithm's efficiency, maintainability, and handling of various scenarios.

✔ Check List (Check all the applicable boxes)
 My code follows the code style of this project.
 This PR does not contain plagiarized content.
 The title of my pull request is a short description of the requested changes.

📄 Note to reviewers
This pull request aims to add the new algorithm implementation in C, C++,Java and Python. The proposed changes include code refactoring, algorithmic optimizations, and adherence to best practices. These updates enhance the readability, efficiency, and maintainability of the implementation. Your valuable feedback on the changes and suggestions for further enhancements are highly appreciated. Thank you for taking the time to review this pull request.

## 📷 Screenshots
![c](https://github.com/Kumar-laxmi/Algorithms/assets/105485872/3c8b7527-9a1b-49ed-93a0-33c081abf692)
![c++](https://github.com/Kumar-laxmi/Algorithms/assets/105485872/5ccdf88b-a021-4eff-b94c-d9870d6d5d8e)
![java](https://github.com/Kumar-laxmi/Algorithms/assets/105485872/2cde3a56-2e72-41d7-8b67-ec5f01a58887)
![python](https://github.com/Kumar-laxmi/Algorithms/assets/105485872/6baac79b-3d01-4800-9a65-c153acf67785)

2023-06-12 05:25 UTC, Kumar-laxmi requested changes
Please place the programs into ```Pattern Matching``` folder

2023-06-13 08:46 UTC, Arun9739 approved these changes

2023-06-13 11:11 UTC, zugzwang03 approved these changes

2023-06-15 15:52 UTC, mrigankabrahma commented
@Aarsh30 assign me this issue

2023-06-16 08:43 UTC, 072arushi approved these changes

2023-06-19 10:46 UTC, Kumar-laxmi approved these changes

2023-06-20 05:18 UTC, zugzwang03 approved these changes

2023-06-20 05:37 UTC, Aarsh30 commented
@Kumar-laxmi  whatever changes you have told everything is done and codefactor issuse also had been solved

2023-06-20 11:26 UTC, Kumar-laxmi approved these changes

2023-06-20 11:27 UTC, merged