Add Luhn algorithm in C,C++,Python and Java
Kumar-laxmi/Algorithms pull request #1321
Opened 2023-06-15 16:11 UTC by Ikshvaku24

## 🛠️ Issue (#1149)

## 👨‍💻 Changes proposed
Added Luhn Algorithm in C,C++,Python and Java

## ✔️ Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers

## 📷 Screenshots
![Luhn_algo](https://github.com/Kumar-laxmi/Algorithms/assets/111303252/c78b7c33-bafa-44f1-9a77-8d32481c5b5d)

2023-06-16 01:22 UTC, Kumar-laxmi requested changes
![image](https://github.com/Kumar-laxmi/Algorithms/assets/76027425/5181e383-ab7b-4c12-a222-b2232b21fc99)

Does it mean your contribution doesn't follow any of these?

2023-06-16 03:10 UTC, Ikshvaku24 commented
Left by mistake. Done the changes.

2023-06-16 04:17 UTC, zugzwang03 approved these changes

2023-06-16 08:42 UTC, 072arushi approved these changes

2023-06-17 16:05 UTC, Arun9739 approved these changes

2023-07-03 13:06 UTC, zugzwang03 approved these changes

2023-07-11 06:43 UTC, Kumar-laxmi approved these changes

2023-07-11 06:45 UTC, merged