Added Stooge Sort Algorithm in C, C++ , Java and Python
Kumar-laxmi/Algorithms pull request #1322
Opened 2023-06-15 16:18 UTC by dhrupad17

## 🛠️ Issue (Number)

Issue no #1305 

## 👨‍💻 Changes proposed

I have added Stooge Sort Algorithm in C , C++, Java and Python

```About Stooge Sort```

The Stooge Sort algorithm is a recursive sorting algorithm that divides the array into two parts and recursively sorts the first two-thirds and the last two-thirds of the array. It works by comparing the first and last elements of the range and swapping them if necessary. Then, it recursively sorts the first two-thirds and the last two-thirds of the array, and finally sorts the first two-thirds again. This process is repeated until the entire array is sorted. Although the algorithm has a relatively high time complexity of O(n^(log3/log1.5)) and is not considered efficient for large arrays, it serves as a good learning tool to understand recursion and divide-and-conquer algorithms.

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers

@Kumar-laxmi Please review it and merge my PR.

## 📷 Screenshots

### C Code Implementation

![Screenshot (492)](https://github.com/Kumar-laxmi/Algorithms/assets/91726340/37ce5fa2-38f1-4dcd-81d4-ab69d45daa0d)

### C++ Code Implementation

![Screenshot (493)](https://github.com/Kumar-laxmi/Algorithms/assets/91726340/c6f9f19a-a17e-40a4-b784-ddab78b2d103)

### Python Code Implementation

![Screenshot (494)](https://github.com/Kumar-laxmi/Algorithms/assets/91726340/1003f7a2-9871-46c4-ab14-1c13dd2a1b2b)

### Java Code Implementation

![Screenshot (496)](https://github.com/Kumar-laxmi/Algorithms/assets/91726340/b7130b1f-9bf1-4ec2-9a96-4c870908dbd9)

2023-06-16 01:19 UTC, Kumar-laxmi requested changes
When you are asked for screen shots, it is expected to post output screenshots and not the screenshot of code. Your code is already visible to us.

2023-06-16 03:20 UTC, dhrupad17 commented
@Kumar-laxmi  I have Updated my pull request with input and output screenshots. Kindly review and merge.

2023-06-16 04:14 UTC, zugzwang03 approved these changes

2023-06-16 08:42 UTC, 072arushi approved these changes

2023-06-17 16:06 UTC, Arun9739 approved these changes

2023-06-30 02:21 UTC, Kumar-laxmi approved these changes

2023-06-30 02:22 UTC, merged