Diffie hellman
Kumar-laxmi/Algorithms pull request #1352
Opened 2023-06-16 09:36 UTC by SPARSH1608

## 🛠️ Issue (Number)

Issue no #687

## 👨‍💻 Changes proposed
Add Diffie - Hellman Algorithm in C , C++ and java 

Will add Diffie - Hellman Algorithm with adequate comments for readers to get a clear understanding.
To add in JAVA / C++ and C

## ✔️ Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

![java111](https://github.com/Kumar-laxmi/Algorithms/assets/100155097/84a66693-5ac7-4e1f-83a4-b41a39da5ef3)
![c++11](https://github.com/Kumar-laxmi/Algorithms/assets/100155097/4eb0c2e6-79fa-420d-8dae-3a0948ccab0b)
![c111](https://github.com/Kumar-laxmi/Algorithms/assets/100155097/fadb0e16-7638-4c42-80e4-ee542de7adc5)

2023-06-20 04:40 UTC, Kumar-laxmi requested changes
Remove all the files other than Diffie Helman

2023-06-20 05:14 UTC, zugzwang03 approved these changes

2023-06-20 15:31 UTC, SPARSH1608 commented
> Remove all the files other than Diffie Helman

in cryptography folder? they are other programs in there as well

2023-06-23 10:19 UTC, 072arushi approved these changes

2023-06-29 04:48 UTC, Kumar-laxmi commented
> > Remove all the files other than Diffie Helman
> 
> in cryptography folder? they are other programs in there as well

![image](https://github.com/Kumar-laxmi/Algorithms/assets/76027425/1439ec5b-a801-4171-842e-dc6f4ebaaa95)

This PR is only for Diffie Hellman, but you are pushing other programs too, kindly make necessary changes ASAP

2024-05-12 16:44 UTC, closed without merging