Heron's Formula #1155 added in all 4 languages
Kumar-laxmi/Algorithms pull request #1354
Opened 2023-06-16 11:31 UTC by swastik-akhil

## 🛠️ Issue (#1155)

## 👨‍💻 Changes proposed

- [x] Added Heron's formula code in C, C++, Java, Python.

## 📝Note

1.  My code follows the code style of this project.
2.  This PR does not contain plagiarized content.
3.  The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers

I have myself reviewed all 4 files and all of them are working correctly.

## 📷 Screenshots
![herons jpg](https://github.com/Kumar-laxmi/Algorithms/assets/126651810/19346b8e-1733-4249-8e0a-19c20a65e77c)

2023-06-16 11:42 UTC, swastik-akhil commented
@Kumar-laxmi I have completed this issue and hence I would like to draw your attention towards it.

2023-06-17 01:17 UTC, Kumar-laxmi requested changes
Place java program in ```Java/Maths``` folder

2023-06-17 06:00 UTC, zugzwang03 requested changes

2023-06-17 06:00 UTC, zugzwang03 commented on heronsFormula.java
Put this under Java directory.

2023-06-17 10:47 UTC, swastik-akhil commented
I have done the changes, kindly check @Kumar-laxmi @zugzwang03

2023-06-17 16:27 UTC, Arun9739 approved these changes

2023-06-18 05:06 UTC, zugzwang03 commented on C++/Maths/heronsFormula.CPP
make this .cpp

2023-06-18 16:32 UTC, 072arushi approved these changes

2023-06-19 04:52 UTC, zugzwang03 approved these changes

2023-06-19 12:12 UTC, swastik-akhil commented
> Place java program in `Java/Maths` folder

Resolved

2023-06-27 14:20 UTC, Kumar-laxmi approved these changes

2023-06-27 14:21 UTC, merged