ADDED: Skip_List_Algorithm SSOC'23
Kumar-laxmi/Algorithms pull request #1373
Opened 2023-06-17 05:12 UTC by shravanii2308

## 🛠️ Issue (#1209 )

Issue no #1209

## 👨‍💻 Changes proposed
Added skip list algorithm in C++, C, Python and Java under Linked List.

## ✔️ Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers
Please review my PR

## 📷 Screenshots\
In C++
[
![image](https://github.com/Kumar-laxmi/Algorithms/assets/113932534/c024e5ed-6a45-4ce9-bb13-505ffc216a9e)
](url)

In C
[
![image](https://github.com/Kumar-laxmi/Algorithms/assets/113932534/6846afc6-575c-40be-bec5-c4982a15ea21)
](url)

In Java
[
![image](https://github.com/Kumar-laxmi/Algorithms/assets/113932534/b6d3a01c-11eb-46df-857c-e3b5608c4b02)
](url)

In Pyhton
[
![image](https://github.com/Kumar-laxmi/Algorithms/assets/113932534/15f48af8-3ecb-488b-95a6-11e5d3196362)
](url)

2023-06-17 05:59 UTC, zugzwang03 approved these changes

2023-06-17 16:25 UTC, Arun9739 approved these changes

2023-06-23 10:18 UTC, 072arushi approved these changes

2023-07-03 04:39 UTC, Kumar-laxmi approved these changes

2023-07-03 04:41 UTC, Kumar-laxmi requested changes
Kindly rectify the CodeFactor issues

2023-07-19 06:17 UTC, closed without merging