Implemented Fast Fourier Transform
Kumar-laxmi/Algorithms pull request #1394
Opened 2023-06-17 16:48 UTC by Aryan-d13

## 🛠️ Closes Issue #1313 
Issue no #1313

Implemented Fast Fourier Transform in Java, C, C++, Python

- [✔️ ] My code follows the code style of this project.
- [ ✔️] This PR does not contain plagiarized content.
- [ ✔️] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewer
I've Implemented the FFT and tested the Output in the most Effiecient way I could, I had to create the Complex class in Java on my own as it wasn't available on Apache servers anymore

## 📷 Screenshots
![image](https://github.com/Kumar-laxmi/Algorithms/assets/128261659/f47b0428-023a-450d-9418-a349f30e11d5)
![image](https://github.com/Kumar-laxmi/Algorithms/assets/128261659/994ff814-f5b6-4ec1-abeb-aed7574ebe96)
![image](https://github.com/Kumar-laxmi/Algorithms/assets/128261659/f904f78f-84d1-47f6-8fbc-bbc68dad9c97)
![image](https://github.com/Kumar-laxmi/Algorithms/assets/128261659/e1f384da-9711-4797-ab54-db1e9f9fb51e)

2023-06-17 16:49 UTC, Aryan-d13 commented
Closes Issue #1313

2023-06-18 01:11 UTC, Kumar-laxmi requested changes
You are required to put the screen shot of your output and not the code, code is already visible in the CodeSpace

2023-06-18 04:54 UTC, zugzwang03 commented on Java/Signal Processing/FFT.java
change this name here

2023-06-18 13:43 UTC, Aryan-d13 commented
@Kumar-laxmi @zugzwang03 Please review the changes

2023-06-18 16:31 UTC, 072arushi approved these changes

2024-05-08 16:44 UTC, closed without merging