interpolation_search code in c , c++ , java , python
Kumar-laxmi/Algorithms pull request #1409
Opened 2023-06-18 11:24 UTC by mandliyarajendra11

## 🛠️ Issue (Number)
#1366 

## ✔️ Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers

Given a sorted array of n uniformly distributed values arr[], write a function to search for a particular element x in the array.
Linear Search finds the element in O(n) time, Jump Search takes O(√n) time and Binary Search takes O(log n) time.
The Interpolation Search is an improvement over Binary Search for instances, where the values in a sorted array are uniformly distributed. Interpolation constructs new data points within the range of a discrete set of known data points. Binary Search always goes to the middle element to check. On the other hand, interpolation search may go to different locations according to the value of the key being searched. For example, if the value of the key is closer to the last element, interpolation search is likely to start search toward the end side

```

Step1: In a loop, calculate the value of “pos” using the probe position formula. 
Step2: If it is a match, return the index of the item, and exit. 
Step3: If the item is less than arr[pos], calculate the probe position of the left sub-array. Otherwise, calculate the same in the right sub-array. 
Step4: Repeat until a match is found or the sub-array reduces to zero.
```

2023-06-18 16:31 UTC, 072arushi requested changes
Add screenshots of input and output as well

2023-06-19 04:53 UTC, zugzwang03 approved these changes

2023-06-19 05:50 UTC, mandliyarajendra11 commented
> Add screenshots of input and output as well

done

2023-06-20 05:06 UTC, zugzwang03 approved these changes

2023-06-23 10:17 UTC, 072arushi approved these changes

2023-06-28 09:01 UTC, mandliyarajendra11 commented
@Kumar-laxmi please merge

2023-06-30 02:12 UTC, Kumar-laxmi approved these changes

2023-06-30 02:14 UTC, merged