Added Edmonds-karp Algorithm Successfully after Re-Forking
Kumar-laxmi/Algorithms pull request #1421
Opened 2023-06-19 03:30 UTC by neeraj542

## 🛠 Issue (#718)

Issue no #718

## 👨‍💻 Changes proposed
This pull request aims to enhance the efficiency and broaden the applicability of the Edmonds-Karp algorithm implementation by adding support for C, Java, and Python programming languages. The proposed changes include optimized C++ code for improved performance, Java code for wider language compatibility, and Python code for greater versatility. Additionally, enhanced documentation has been included to aid developers in understanding and utilizing the algorithm in multiple programming languages. These updates aim to provide developers with efficient and accessible solutions for maximum flow problems in C++, Java, and Python environments.

Please review the changes and consider merging them into the main repository.

## ✔ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers
In the pseudocode, 'V' represents the number of vertices in the graph, 'residualGraph' refers to the residual capacities of the graph, and the graph represents the original 'graph' with capacities.

Thank you for reviewing this pull request. The changes include optimizations to the Edmonds-Karp algorithm implementation and the addition of Python code for improved versatility. Your feedback and suggestions are valuable to us, and we welcome any recommendations to enhance the algorithm further. We appreciate your time and collaboration in making this implementation more efficient and scalable.

## 📷 Screenshots
Python
![image](https://github.com/Kumar-laxmi/Algorithms/assets/114648043/e936c4dc-e908-4405-83de-2e9292608eab)

C++
![image](https://github.com/Kumar-laxmi/Algorithms/assets/114648043/4bc97677-65b1-48a7-af84-17ed52d81e6d)

C 
![image](https://github.com/Kumar-laxmi/Algorithms/assets/114648043/fa6f9fc9-1de5-4665-b23c-d6422625ce76)

JAVA
![image](https://github.com/Kumar-laxmi/Algorithms/assets/114648043/72f67fec-1084-42f2-a2cc-795abfcf9f8b)

2023-06-19 03:36 UTC, Kumar-laxmi requested changes
Screen shot of output not the code

2023-06-19 04:46 UTC, zugzwang03 approved these changes

2023-06-19 05:02 UTC, neeraj542 commented
> Screen shot of output not the code

Thanks @Kumar-laxmi for reminding me, updated it!

2023-06-23 01:49 UTC, Kumar-laxmi commented
@Arun9739 @072arushi Kindly review this PR

2023-06-23 10:11 UTC, 072arushi approved these changes

2023-06-24 18:31 UTC, Arun9739 approved these changes

2023-06-29 04:51 UTC, Kumar-laxmi approved these changes

2023-06-29 04:52 UTC, merged