Added Bellman Ford Algorithm in C, Java and Python
Kumar-laxmi/Algorithms pull request #1432
Opened 2023-06-19 12:36 UTC by Anushka-gupta496

## 🛠️ Issue (Number)

Issue no #1350 

## 👨‍💻 Changes proposed
 Added Bellman Ford Algorithm in C, Java and Python

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots
Java:

![image](https://github.com/Kumar-laxmi/Algorithms/assets/98311688/24e24da4-c9ec-4b64-abbb-3fa86c469f95)

Python:

![image](https://github.com/Kumar-laxmi/Algorithms/assets/98311688/f246c415-d62f-4260-bd92-4e254324eb05)

C:

![image](https://github.com/Kumar-laxmi/Algorithms/assets/98311688/713d8031-fa7e-4135-adea-87554357a55f)

2023-06-19 15:14 UTC, Kumar-laxmi requested changes
Remove the file ```C++/Machine-Learning/_K-nearest-neighbour-algo.cpp``` from the PR

2023-06-20 05:04 UTC, zugzwang03 approved these changes

2023-06-21 16:28 UTC, Arun9739 approved these changes

2023-06-23 10:16 UTC, 072arushi approved these changes

2023-07-07 06:13 UTC, Kumar-laxmi commented
Still the file is visible in this PR's codespace

2023-07-30 11:55 UTC, closed without merging