Circular Linked List in JAVA
Kumar-laxmi/Algorithms pull request #1457
Opened 2023-06-20 15:04 UTC by Devchawla2608

A circular linked list is a type of linked list where the last node's next pointer points back to the first node, creating a circular structure. Unlike a regular linked list, which has a null or "tail" pointer at the end, a circular linked list does not have a distinct end. This circular arrangement allows for continuous traversal and enables efficient operations on the list.

## 🛠️ Issue (1402)

## 👨‍💻 Changes proposed
I have added solution and explanation to the problem of Circular Linked List
Made program menu driven.

## ✔️ Check List (Check all the applicable boxes) 

- [✅] My code follows the code style of this project.
- [✅] This PR does not contain plagiarized content.
- [✅] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers
Insert nodes into the list:
a. Create a new node with the given data.
b. If the head is null, make the new node the head and set its next pointer to itself, forming a circular reference.
c. If the head is not null, traverse the list until the last node is reached (i.e., the node whose next pointer points to the head).
d. Set the next pointer of the last node to the new node.
e. Set the next pointer of the new node to the head, completing the circular reference.

Traverse the circular linked list:
a. Set a temporary node variable to the head.
b. Start a loop that continues until the temporary node variable becomes equal to the head again (indicating completion of a full traversal).
c. Within the loop, process the data of the current node.
d. Update the temporary node variable to its next pointer for the next iteration.

## 📷 Screenshots
![image](https://github.com/Kumar-laxmi/Algorithms/assets/92145696/5365ce5f-aff5-4fc6-9b76-11ec525bedb4)

2023-06-21 15:35 UTC, 072arushi approved these changes

2023-06-22 04:34 UTC, zugzwang03 approved these changes

2023-06-22 14:57 UTC, Kumar-laxmi requested changes
Update function is missing

2023-06-22 16:17 UTC, Devchawla2608 commented
The update function is implemented. Please review it

2023-06-24 18:26 UTC, Arun9739 approved these changes

2023-06-27 12:49 UTC, zugzwang03 approved these changes

2023-07-18 01:38 UTC, Kumar-laxmi approved these changes

2023-07-18 01:39 UTC, merged