Quick Select Algorithm
Kumar-laxmi/Algorithms pull request #1525
Opened 2023-06-22 13:20 UTC by harshitaaa8

## 🛠️ Issue (#1368 )

Issue no #1368 

## 👨‍💻 Changes proposed
Added Quick Select Algorithm in c, c++, java, python

## ✔️ Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers
I have checked all the 4 files are giving the desirable results.
![Screenshot 2023-06-22 183408](https://github.com/Kumar-laxmi/Algorithms/assets/121786696/8bf6cedb-88e8-44bc-a631-287690f03b3f)

## 📷 Screenshots

2023-06-23 02:33 UTC, Kumar-laxmi requested changes
All the program files are missing the extension

2023-06-23 02:34 UTC, Kumar-laxmi commented
![image](https://github.com/Kumar-laxmi/Algorithms/assets/76027425/59ba7787-4030-4a9d-886f-0260c42469fa)

@harshitaaa8 Does it mean your PR doesn't follow any of those guidelines

2023-06-23 04:29 UTC, zugzwang03 requested changes
name the files properly

2023-06-23 09:53 UTC, harshitaaa8 commented
I have added the extensions and checked the boxes as it follows the guidelines.

2023-06-23 10:09 UTC, 072arushi approved these changes

2023-06-23 11:44 UTC, zugzwang03 commented on C++/Searching/Quick Select Algorithm.cpp
don't keep space in file names

2023-06-23 12:41 UTC, harshitaaa8 commented on C++/Searching/Quick Select Algorithm.cpp
Okay.
Have done the changes.

2023-06-24 18:41 UTC, Arun9739 approved these changes

2023-06-25 05:44 UTC, zugzwang03 approved these changes

2023-06-28 04:26 UTC, Kumar-laxmi reviewed
These programs seems to be copied from https://www.geeksforgeeks.org/quickselect-algorithm/

2023-06-28 13:03 UTC, harshitaaa8 commented
I have referred to the site but I did not mean to add plagiarized code 
I sincerely apologize and will make sure this is not repeated.
I can close this issue and raise a new issue where I will make sure to not repeat my mistake.

2023-06-29 16:06 UTC, closed without merging