added worst fit memory allocation technique for cpp, c, python & java closes #1492
Kumar-laxmi/Algorithms pull request #1543
Opened 2023-06-23 09:50 UTC by ranjanmangla1

## 🛠️ Issue #1492 

Issue no #1492 

## 👨‍💻 Changes proposed

Added worst fit algorithm in c, cpp, java & python

## ✔️ Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers

## 📷 Screenshots

2023-06-23 10:14 UTC, 072arushi requested changes
complete description

2023-06-23 10:22 UTC, ranjanmangla1 commented
> complete description

Can you tell me for what you need a complete description?

2023-06-23 10:49 UTC, Kumar-laxmi requested changes
remove fcfs from this PR

2023-06-23 11:25 UTC, zugzwang03 commented on C++/Job Scheduling/fcfs.cpp
remove this file

2023-06-23 12:36 UTC, ranjanmangla1 commented on C++/Job Scheduling/fcfs.cpp
@zugzwang03 deleted it

2023-06-24 18:40 UTC, Arun9739 requested changes
@ranjanmangla1 Add output screenshots

2023-06-25 05:44 UTC, zugzwang03 approved these changes

2023-06-30 16:51 UTC, ranjanmangla1 commented
> @ranjanmangla1 Add output screenshots

Done. Added Output Screenshots @Arun9739. Please review this pull request @Kumar-laxmi @072arushi @Arun9739

2023-07-04 18:31 UTC, Arun9739 approved these changes

2023-07-08 07:26 UTC, 072arushi approved these changes

2023-07-19 06:24 UTC, Kumar-laxmi approved these changes

2023-07-19 06:26 UTC, merged