FCFS-4 files added in job scheduling
Kumar-laxmi/Algorithms pull request #1551
Opened 2023-06-23 16:52 UTC by brahmamyv

## 🛠️ Issue (Number)

Issue no #1444 

## 👨‍💻 Changes proposed
Added Python, Java, C and CPP files of FCFS Algorithm.

## ✔️ Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers

## 📷 Screenshots
![python_op](https://github.com/Kumar-laxmi/Algorithms/assets/130195097/cbe59fb7-6cb5-4344-ba7f-ff28425eedf8)

![javaop1](https://github.com/Kumar-laxmi/Algorithms/assets/130195097/d81e69b2-d372-442b-a7fd-88cf18176c26)
![javaop2](https://github.com/Kumar-laxmi/Algorithms/assets/130195097/1042ab8a-cc64-44a3-acc6-d6f97d761a9b)

![c-op](https://github.com/Kumar-laxmi/Algorithms/assets/130195097/528d15a7-4231-49b8-abff-1b9a4ca396eb)

![c++op](https://github.com/Kumar-laxmi/Algorithms/assets/130195097/d386ac77-0923-4245-b876-2817888bdb17)

2023-06-24 01:04 UTC, Kumar-laxmi requested changes
Rename all the files as ```First_Come_First_Serve.<extension>```

2023-06-24 05:31 UTC, zugzwang03 approved these changes

2023-06-25 05:52 UTC, zugzwang03 approved these changes

2023-06-27 18:42 UTC, Arun9739 approved these changes

2023-07-08 07:25 UTC, 072arushi approved these changes

2023-07-08 12:59 UTC, brahmamyv commented
@Kumar-laxmi sir review the changes .Files name changed!

2023-07-12 01:36 UTC, Kumar-laxmi approved these changes

2023-07-12 01:37 UTC, merged