Ford Fulkerson Algorithm is implemented in C , CPP , JAVA , PYTHON la…
Kumar-laxmi/Algorithms pull request #1552
Opened 2023-06-23 17:39 UTC by Devchawla2608

Ford-Fulkerson is a graph algorithm used to find the maximum flow in a flow network. It iteratively finds augmenting paths from the source to the sink and updates the flow along those paths until no more augmenting paths exist.

## 🛠️ Issue (1510)

Issue no #

## 👨‍💻 Changes proposed

## ✔️ Check List (Check all the applicable boxes) 

- [✅ ] My code follows the code style of this project.
- [✅ ] This PR does not contain plagiarized content.
- [✅ ] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers

1.) Start with the original graph.
2.) Initialize an empty set S to keep track of the vertices in the cut and an empty cut weight W.
3.) While there are more than 1 vertex in the graph:
4.) Choose an arbitrary vertex v not yet in S.
5.) Add v to S.
6.) Compute the minimum cut between S and the remaining vertices using a modified version of the Max Flow algorithm (such as the Ford-Fulkerson algorithm).
7.) Update W to be the maximum of the current W and the cut weight obtained from the minimum cut.
8.) Return the final cut weight W.

## 📷 Screenshots
![image](https://github.com/Kumar-laxmi/Algorithms/assets/92145696/a0403ab7-c1df-4966-a97d-8b2202a4deb3)

2023-06-24 01:07 UTC, Kumar-laxmi commented
You haven't included the link to you issue (just normally type issue number after '#')

2023-06-24 04:53 UTC, Kumar-laxmi requested changes
This issue is only in C and Java

2023-06-24 05:24 UTC, zugzwang03 approved these changes

2023-06-24 11:34 UTC, Devchawla2608 commented
@Kumar-laxmi 
Changes Done

2023-06-24 17:27 UTC, 072arushi approved these changes

2023-06-27 18:10 UTC, Arun9739 approved these changes

2023-07-19 06:20 UTC, Kumar-laxmi approved these changes

2023-07-19 06:21 UTC, merged