added lcs code in python
Kumar-laxmi/Algorithms pull request #1558
Opened 2023-06-24 04:49 UTC by SimranLahrani842

## 🛠️ Issue (Number)
Issue no #1475 

## 👨‍💻 Changes proposed

Written code in python,along with it printed the entire matrix so that one can easily understand.The lcs string along with the length is printed.
## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers

## 📷 Screenshots
![ss1](https://github.com/Kumar-laxmi/Algorithms/assets/100008872/e8a1b87f-b28f-4982-8843-9d8e71af26f5)

2023-06-24 04:51 UTC, Kumar-laxmi requested changes
rename the file as "Longest_Common_Subsequence.py"

2023-06-24 05:25 UTC, zugzwang03 approved these changes

2023-06-24 05:37 UTC, SimranLahrani842 commented
> rename the file as "Longest_Common_Subsequence.py"

Done Sir👍

2023-06-25 18:42 UTC, SimranLahrani842 commented
@Arun9739 and @072arushi please review

2023-06-27 18:44 UTC, Arun9739 approved these changes

2023-07-08 07:24 UTC, 072arushi approved these changes

2023-07-28 11:36 UTC, Kumar-laxmi approved these changes

2023-07-28 11:37 UTC, merged