Fenwick Tree code in C, C++, Java and Python
Kumar-laxmi/Algorithms pull request #1627
Opened 2023-06-29 18:24 UTC by RashmiK35

## 🛠️ Issue #1600 

## 👨‍💻 Changes proposed

Added c , c++ , python and Java program files for a topic Fenwick Tree

## ✔️ Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers

Added comments for better understanding

## 📷 Screenshots

JAVA CODE

![Screenshot (69)](https://github.com/Kumar-laxmi/Algorithms/assets/93033676/8059aa6b-822e-44f1-b2db-0de323d5745a)

PYTHON CODE 

![Screenshot (70)](https://github.com/Kumar-laxmi/Algorithms/assets/93033676/4ffe5c2f-84ce-4cb3-907b-4e4422f84277)

C CODE

![Screenshot (71)](https://github.com/Kumar-laxmi/Algorithms/assets/93033676/bd21452d-d7ba-4c48-be39-791c640b3b0b)

C++ CODE

![Screenshot (72)](https://github.com/Kumar-laxmi/Algorithms/assets/93033676/244ae1a4-e2b6-4721-a071-203642aef23e)

2023-06-30 00:46 UTC, Kumar-laxmi requested changes
- File extensions are missing
- You are expected to post output screen shot instead of code space screenshots

2023-06-30 05:13 UTC, zugzwang03 approved these changes

2023-06-30 05:39 UTC, RashmiK35 commented
File extensions are added
Output screenshots are added

2023-07-04 18:28 UTC, Arun9739 approved these changes

2023-07-08 07:23 UTC, 072arushi approved these changes

2023-07-13 01:33 UTC, Kumar-laxmi approved these changes

2023-07-13 01:34 UTC, merged