added 0/1 knapsack in Java -> Dynamic-Programming. Issue #72
Kumar-laxmi/Algorithms pull request #164
Opened 2023-01-04 06:54 UTC by harshraj9988

## 🛠️ Issue #72 0/1 Knapsack - Dynamic Programming approach 

## 👨‍💻 Changes proposed

- Added code for 0/1 Knapsack (Dynamic Programming)
- Updated README.md
## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers

Added 0-1 Knapsack (Dynamic-Programming) in Java

recursion -> memoization -> tabulation -> space optimzation

Starting with the naive recursive solution and gradually improving time complexity with memoization, then addressing the space complexity with tabulation and finally with space optimization.

Reorganized README.md and renamed 0/1 knapsack java file
Resolved merge conflict

(mentioned time complexity and space complexity of each approach)

2023-01-05 15:35 UTC, Kumar-laxmi commented
@harshraj9988 Please resolve the **MERGE CONFLICT**

2023-01-05 16:40 UTC, harshraj9988 commented
Resolved Merge Conflict.
Kindly review again.

2023-01-06 04:24 UTC, Kumar-laxmi requested changes

2023-01-06 04:24 UTC, Kumar-laxmi commented on README.md
> +
There some error in the table of README.md

2023-01-06 04:34 UTC, Kumar-laxmi commented
@harshraj9988 Please don't update the README.md as there has to be some changes in it, please remove updations of README.md from this PR

2023-01-06 04:42 UTC, harshraj9988 commented
sure! will remove README.md from this PR

2023-01-06 04:47 UTC, closed without merging