Kruskals Algorithm In C, Cpp, Java and Python
Kumar-laxmi/Algorithms pull request #1644
Opened 2023-07-01 02:23 UTC by derphalesh

## **🛠️ Issue**
### Issue no https://github.com/Kumar-laxmi/Algorithms/issues/1459

## **👨‍💻 Changes proposed**
### Added Kruskals Algorithm in C, Cpp, Java and Python
## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers

Please review the changes in each implementation and provide feedback on the code structure, algorithm implementation, and any potential improvements.
Thank you for your time and valuable feedback.

Best regards,
Phalesh Kolpe
## 📷 Screenshots
![WhatsApp Image 2023-07-01 at 07 36 51](https://github.com/Kumar-laxmi/Algorithms/assets/108562595/62e3f6d8-ce7d-43e0-b4ab-0adf6622c234)

![WhatsApp Image 2023-07-01 at 07 31 04](https://github.com/Kumar-laxmi/Algorithms/assets/108562595/ca3ad8ff-7a55-44d9-a92d-c437fe817238)

![image](https://github.com/Kumar-laxmi/Algorithms/assets/108562595/8b63ae79-8683-4e07-a33f-d4c80ca77843)

2023-07-02 02:11 UTC, Kumar-laxmi requested changes
![image](https://github.com/Kumar-laxmi/Algorithms/assets/76027425/8027aaa5-e11d-4365-b9a0-370db48455a3)

Don't delete any file

2023-07-02 02:56 UTC, derphalesh commented
> ![image](https://user-images.githubusercontent.com/76027425/250326264-8027aaa5-e11d-4365-b9a0-370db48455a3.png)
> 
> Don't delete any file

sorry happened mistakenly I have corrected it

2023-07-02 04:04 UTC, zugzwang03 approved these changes

2023-07-04 18:47 UTC, Arun9739 approved these changes

2023-07-07 01:33 UTC, Kumar-laxmi approved these changes

2023-07-07 01:34 UTC, merged