Elgamal
Kumar-laxmi/Algorithms pull request #1655
Opened 2023-07-02 06:03 UTC by Aarsh30

Addition of Elgamal crypto system
## 🛠️ Issue (#1556)

Issue no #1556 

## ✔️ Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## 📄 Algorithm
ElGamal encryption is a public-key cryptosystem. It uses asymmetric key encryption for communicating between two parties and encrypting the message. This cryptosystem is based on the difficulty of finding discrete logarithm in a cyclic group that is even if we know ga and gk, it is extremely difficult to compute gak.

Idea of ElGamal cryptosystem:
Suppose Alice wants to communicate with Bob.

Bob generates public and private keys:
Bob chooses a very large number q and a cyclic group Fq.
From the cyclic group Fq, he choose any element g and
an element a such that gcd(a, q) = 1.
Then he computes h = ga.
Bob publishes F, h = ga, q, and g as his public key and retains a as private key.
Alice encrypts data using Bob’s public key :
Alice selects an element k from cyclic group F
such that gcd(k, q) = 1.
Then she computes p = gk and s = hk = gak.
She multiples s with M.
Then she sends (p, Ms) = (gk, Ms).
Bob decrypts the message :
Bob calculates s′ = pa = gak.
He divides M*s by s′ to obtain M as s = s′.

## 📷 Screenshots
![c](https://github.com/Kumar-laxmi/Algorithms/assets/105485872/e2c1ce7b-a9f6-45b9-ad1e-646786671bfc)
![c++](https://github.com/Kumar-laxmi/Algorithms/assets/105485872/204815ff-01fe-4722-8da5-3d781bc0d788)
![java](https://github.com/Kumar-laxmi/Algorithms/assets/105485872/5e838253-70c9-4831-a24b-01c7b946461f)
![python](https://github.com/Kumar-laxmi/Algorithms/assets/105485872/b71b67c0-95dd-418d-bc31-1e018a4a1411)

2023-07-02 09:35 UTC, Kumar-laxmi requested changes
Remove the programs of Pollard Rho Algorithm from this PR, make a separate PR for that program

2023-07-04 18:51 UTC, Arun9739 requested changes
@Aarsh30 Take input from user

2023-07-05 03:41 UTC, zugzwang03 approved these changes

2023-07-06 12:03 UTC, Aarsh30 commented
changes whatever were told had been done !

2023-07-08 07:19 UTC, 072arushi approved these changes

2023-07-16 04:56 UTC, Kumar-laxmi approved these changes

2023-07-16 04:58 UTC, merged