Detection loop in linked list
Kumar-laxmi/Algorithms pull request #1694
Opened 2023-07-07 12:05 UTC by NupurHardiya

Issue no. #1403 
--------------------------------------------------------------------------------------------------------------------------------------------
Here are the steps involved in the approach used to detect of a cycle in a linked list using a hash table:

1. Create a hash table to store the addresses of all the nodes in the linked list. Start traversing the linked list, and for each node, 2. check if the node's address is already in the hash table.
3. If the node's address is already in the hash table, then the linked list contains a loop.
4. Otherwise, the node's address is added to the hash table, and the traversal continues.
5. The code returns "The linked list contains a loop" if the linked list contains a loop, and "The linked list does not contain a loop." otherwise.
--------------------------------------------------------------------------------------------------------------------------------------------
- [✅] My code follows the code style of this project.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.
-------------------------------------------------------------------------------------------------------------------------------------------
![detection of loop in LL ](https://github.com/Kumar-laxmi/Algorithms/assets/113535580/a03d3a47-7cc5-4fc5-bad8-65cbcb9c30b2)

2023-07-08 04:45 UTC, zugzwang03 reviewed
name the files in .extension format and remove space over there

2023-07-08 07:16 UTC, 072arushi approved these changes

2023-07-08 07:31 UTC, NupurHardiya commented
Hey @zugzwang03 I have done all the changes. please check.

2023-07-12 05:14 UTC, zugzwang03 approved these changes

2023-07-19 18:52 UTC, Arun9739 approved these changes

2023-07-24 01:35 UTC, Kumar-laxmi requested changes
Give the name as ```Detect_Loop_In_Linked_List``` to all the files

2023-07-24 01:35 UTC, Kumar-laxmi commented on Java/Linked-List/detectionLoopInLinkedList/Node.java
> +class Node {
Put this class in ```Java/Linked-List/detectionLoopInLinkedList/LoopDetection.java```

2023-07-24 11:44 UTC, zugzwang03 commented on Java/Linked-List/detectionLoopInLinkedList/loopdetection.java/node.java
you placed file inside file, place it in folder rather

2024-03-26 16:44 UTC, closed without merging