Added Remove Cycle in Linked List in C, C++, Java, & Python.
Kumar-laxmi/Algorithms pull request #1715
Opened 2023-07-11 12:43 UTC by shanvijha30

## 🛠️ Issue (Number)

Issue no #1683

## 👨‍💻 Changes proposed

Added Remove Cycle in Linked List in C, C++, Java and Python.

## ✔️ Check List (Check all the applicable boxes) 

- [ ✔️ ] My code follows the code style of this project.
- [ ✔️ ] This PR does not contain plagiarized content.
- [ ✔️ ] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots

Java
![ll1j](https://github.com/Kumar-laxmi/Algorithms/assets/76652184/4f1eae23-13a4-4b76-bf7a-f7eef866ad45)
![llj2](https://github.com/Kumar-laxmi/Algorithms/assets/76652184/dbf07325-3dcf-4e45-b419-abffb3c23314)
![llj3](https://github.com/Kumar-laxmi/Algorithms/assets/76652184/13bf655d-dce0-4550-97a8-dc85b9fc8f34)

C
![cll1](https://github.com/Kumar-laxmi/Algorithms/assets/76652184/5e9f54c2-16d2-4601-b712-93b6e8d0467b)
![cll2](https://github.com/Kumar-laxmi/Algorithms/assets/76652184/9cd3e2fb-7096-44f2-9c4d-39330ca1e9f7)

C++
![c++ll1](https://github.com/Kumar-laxmi/Algorithms/assets/76652184/8d3a40c2-544d-48a5-9330-7d416ff8d85d)
![c++ll2](https://github.com/Kumar-laxmi/Algorithms/assets/76652184/999e441c-0490-443a-88c1-77d8f95f1604)
![c++ll3](https://github.com/Kumar-laxmi/Algorithms/assets/76652184/3b4e6702-2b3b-433c-bfe9-bf25d62b8a38)

Python
![pyll1](https://github.com/Kumar-laxmi/Algorithms/assets/76652184/084d6e46-e640-42a4-9051-0d8d1f0e122d)
![pyll2](https://github.com/Kumar-laxmi/Algorithms/assets/76652184/d45e5a90-236d-4d8a-8d84-91521a0653d4)
![pyll3](https://github.com/Kumar-laxmi/Algorithms/assets/76652184/dbb515ed-d9cb-4dea-9919-2aacc4f7545e)

Output
![detect_and_remove_loop_output](https://github.com/Kumar-laxmi/Algorithms/assets/76652184/bfdc5f2c-5932-4ff7-84b6-6d7e4d7c464e)

2023-07-12 01:23 UTC, Kumar-laxmi requested changes
Remove LRTF programs

2023-07-12 01:24 UTC, Kumar-laxmi commented
Output screen shot is required not the code's screen shot

2023-07-12 10:57 UTC, zugzwang03 approved these changes

2023-07-12 12:50 UTC, shanvijha30 commented
@Kumar-laxmi Will make the necessary changes.

2023-07-13 11:49 UTC, 072arushi approved these changes

2023-07-21 07:09 UTC, Arun9739 approved these changes

2024-03-24 16:44 UTC, closed without merging