Adding the Sentinel linear Search
Kumar-laxmi/Algorithms pull request #1719
Opened 2023-07-13 03:42 UTC by Aarsh30

Sentinel Linear Search is a variation of the Linear Search algorithm that incorporates a sentinel value to optimize the search process. In traditional linear search, we iterate through each element of an array sequentially until we find the desired value or reach the end of the array. In Sentinel Linear Search, we add a sentinel value, which is the target value we are searching for, at the end of the array. By doing this, we eliminate the need for an additional comparison within the loop to check if we have reached the end of the array

## 🛠️ Issue (#1521)

Issue no ##1521

## ✔️ Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## 📄 Algorithm 
Here is the step-by-step process of the Sentinel Linear Search algorithm:

Initialize the target value to be searched.
Store the last element of the array in a variable, and replace it with the target value.
Set up a loop to iterate through the array from the beginning.
Within the loop, check if the current element is equal to the target value.
If it is, the target value has been found at the last position (the sentinel position). Return the index of the target value.
If it is not, continue iterating through the array.
If the loop completes without finding the target value, it means the target value is not present in the array. Return a value indicating the absence of the target value.

## 📷 Screenshots

![c](https://github.com/Kumar-laxmi/Algorithms/assets/105485872/aa5d26f9-00e1-49ee-ba76-f312d94d6eeb)
![c++](https://github.com/Kumar-laxmi/Algorithms/assets/105485872/28cdd48c-c55d-4977-baaf-0ba4a003004f)
![java](https://github.com/Kumar-laxmi/Algorithms/assets/105485872/9d4d19bf-b3bd-4be9-8439-a9918d73ce2c)
![python](https://github.com/Kumar-laxmi/Algorithms/assets/105485872/8281feeb-fa2d-4c17-a5ae-1e34e2ea30ad)

2023-07-17 01:37 UTC, Kumar-laxmi requested changes
Remove Pollard Rho Algorithm programs from this pr

2023-07-17 04:55 UTC, zugzwang03 approved these changes

2023-07-21 07:29 UTC, Arun9739 approved these changes

2023-07-25 09:25 UTC, 072arushi approved these changes

2024-03-23 16:44 UTC, closed without merging