AStarSearch.cpp
Kumar-laxmi/Algorithms pull request #1729
Opened 2023-07-14 19:14 UTC by RashmiK35

## 🛠️ Issue (Number)

Issue no # 1684

## 👨‍💻 Changes proposed

Added A* Search Algorithm code in C , C++, Java and Python

## ✔️ Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers

## 📷 Screenshots

![Ac](https://github.com/Kumar-laxmi/Algorithms/assets/93033676/5b05c252-bbdf-470d-93a4-1a8cd58e7566)

![Ac++](https://github.com/Kumar-laxmi/Algorithms/assets/93033676/01be9d85-1199-428d-96b0-f16aedfdfeca)

![Screenshot 2023-07-15 003628](https://github.com/Kumar-laxmi/Algorithms/assets/93033676/4923dfb7-ebd8-42ef-ab99-cd7d2aebcf03)

![Apython](https://github.com/Kumar-laxmi/Algorithms/assets/93033676/ab41421b-89e6-414b-889a-4f2787231227)

2023-07-19 06:05 UTC, Kumar-laxmi requested changes
Push these programs in Artificial intelligence Folder

2023-07-19 13:30 UTC, zugzwang03 approved these changes

2023-07-21 10:58 UTC, zugzwang03 requested changes
.cpp placed twice

2023-07-22 18:40 UTC, RashmiK35 commented
Pushed the programs in Artificial intelligence Folder and deleted the recurring file

2023-07-23 04:45 UTC, zugzwang03 approved these changes

2023-07-23 13:46 UTC, Arun9739 approved these changes

2024-03-15 14:47 UTC, closed without merging