added ottmann algorithm in C,C++,Java and Python
Kumar-laxmi/Algorithms pull request #1749
Opened 2023-07-18 17:19 UTC by hlw-aryan

## 🛠️ Issue (Number)

Issue no #1624 Bentley-Ottmann Algorithm

## 👨‍💻 Changes proposed
Implemented the Bentley-Ottmann algorithm for line segment intersection detection.
Provided an efficient and accurate solution to detect intersections among line segments.
The algorithm follows the Bentley-Ottmann approach with a time complexity of O((N + K) log N), where N is the number of segments and K is the number of intersections.

Code changes can be accessed at the following locations:

- C: C/Maths/countLineIntersection.c
- C++: C++/Maths/countLineIntersection.cpp
- Java: Java/Maths/countLineIntersection.java
- Python: Python/Maths/countLineIntersection.py

## ✔️ Check List (Check all the applicable boxes) 

- [✔️] My code follows the project's code style.
- [✔️] This PR does not contain plagiarized content.
- [✔️] The title of my pull request is a clear description of the proposed changes.

## 📄 Note to reviewers
Implemented Bentley-Ottmann algorithm for line segment intersection detection.
Kindly review the code and give feedback accordingly.

## 📷 Screenshots

Please find attached relevant screenshots.
![oto1](https://github.com/Kumar-laxmi/Algorithms/assets/134946530/30d2ce02-99d2-4c4d-9047-8e463e96701c)
![oto 2](https://github.com/Kumar-laxmi/Algorithms/assets/134946530/d1a64364-671f-4d7c-84d5-cad30025b828)
![oto 3](https://github.com/Kumar-laxmi/Algorithms/assets/134946530/990b7a3e-f603-4e99-8b53-662a6fe64f87)
![oto 4](https://github.com/Kumar-laxmi/Algorithms/assets/134946530/53217c8a-2161-4210-b4f3-49fc16eb7f6f)

2023-07-18 17:19 UTC, hlw-aryan commented
@Kumar-laxmi plz review it

2023-07-23 12:10 UTC, Kumar-laxmi requested changes
Rename files as ```Bentley_Ottmann_Algorithm```

2023-07-23 13:48 UTC, Arun9739 approved these changes

2023-07-24 04:36 UTC, zugzwang03 approved these changes

2023-07-25 09:59 UTC, hlw-aryan commented
@Kumar-laxmi plz merge this

2023-07-28 11:27 UTC, Kumar-laxmi approved these changes

2023-07-28 11:27 UTC, merged