Red black tree issue #91
Kumar-laxmi/Algorithms pull request #220
Opened 2023-01-06 08:39 UTC by ManavLohia945

## 🛠️ Issue (Number)

Issue no #91

## 👨‍💻 Changes proposed
None yet 

## ✔️ Check List (Check all the applicable boxes) 

- [ ✔️] My code follows the code style of this project.
- [ ✔️] This PR does not contain plagiarized content.
- [✔️ ] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers
NA

## 📷 Screenshots

2023-01-06 15:57 UTC, ManavLohia945 commented
Ok will do that by tomm

2023-01-07 14:44 UTC, Kumar-laxmi commented
@ManavLohia945 For this PR don't update the **README.md**

2023-01-08 09:53 UTC, ManavLohia945 commented
i have now not updated the README file as instructed by you

2023-01-09 01:20 UTC, Kumar-laxmi commented
Something is wrong with the **README.md** in this PR, please look into it

2023-01-10 08:36 UTC, Kumar-laxmi commented
> Something is wrong with the **README.md** in this PR, please look into it

@ManavLohia945 Please remove the updation of **README.md** from this PR

2023-01-10 08:45 UTC, zugzwang03 requested changes
Add your approach in a  few comment lines

2023-01-11 08:01 UTC, ManavLohia945 commented
@Kumar-laxmi I am so confused as to what should I include in the README.md file. If you tell me exactly what to include in that file it would be appreciated

2023-01-19 15:45 UTC, ManavLohia945 commented
@Kumar-laxmi sir please check this PR. I am very sorry for the delay. I hope the content in the README.md file is correct now .

2023-01-20 18:07 UTC, Sanjanabharadwaj25 requested changes
<img width="645" alt="image" src="https://user-images.githubusercontent.com/77878089/213774373-7f924e34-cc46-4ca5-a9ba-54fd006e380a.png">
@ManavLohia945 The README is not correct. Make the necessary changes.

2023-01-22 07:40 UTC, ManavLohia945 commented
Done plz check @Sanjanabharadwaj25

2023-01-22 11:37 UTC, Sanjanabharadwaj25 commented on README.md
>  | 2.  | Banker's Algorithm | [C](https://github.com/Kumar-laxmi/Algorithms/blob/main/C/Deadlock%20Avoidance/bankers.c), [Python](https://github.com/Kumar-laxmi/Algorithms/blob/main/Python/Deadlock%20
@ManavLohia945 Please resolve this.

2023-01-22 11:39 UTC, Sanjanabharadwaj25 commented
> Done plz check @Sanjanabharadwaj25

<img width="571" alt="image" src="https://user-images.githubusercontent.com/77878089/213913822-1475c123-c698-43a2-b41a-a8444d9ede83.png">
There are still some corrections to be made. Please look into it.

2023-01-23 14:32 UTC, ManavLohia945 commented
Could you send me the link i have to add in the readme file in the red black tree section @Sanjanabharadwaj25

2023-01-23 14:37 UTC, ManavLohia945 commented
Now check @Sanjanabharadwaj25

2023-01-30 06:55 UTC, zugzwang03 approved these changes

2023-02-21 01:24 UTC, Kumar-laxmi commented
@ManavLohia945 You can better close this PR and open a fresh PR with no changes done in the README.md

2023-02-24 09:56 UTC, ManavLohia945 commented
Okay I will keep the readme file as it is in the main branch

2023-02-24 10:07 UTC, closed without merging