code for Banker's Algorithm
Kumar-laxmi/Algorithms pull request #231
Opened 2023-01-07 03:04 UTC by mvpamansingh

## 🛠️ Issue (151)

Issue no #151 

## 👨‍💻 Changes proposed

## ✔️ Check List (Check all the applicable boxes) 

- [ ✔️] My code follows the code style of this project.
- [✔️ ] This PR does not contain plagiarized content.
- [✔️ ] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers

## 📷 Screenshots

2023-01-07 14:53 UTC, Kumar-laxmi requested changes
Changes required:
- Update the title to include "Wave Sort"
- In description please include the issue number of Wave Sort

2023-01-07 14:53 UTC, Kumar-laxmi commented
@mvpamansingh Please resolve the **CodeFactor** issue

2023-01-07 17:50 UTC, mvpamansingh commented
@Kumar-laxmi I have fix the code factor for wave sort algorithm

2023-01-10 09:48 UTC, Kumar-laxmi requested changes
Changes to be done:
- Remove folder ```.vscode```
- Update the PR title to : "Bankers Algorithm, Travelling Salesman Problem, Sliding Window and Wave Sort algorithm"

2023-01-10 09:51 UTC, Kumar-laxmi commented on Java/Sliding Window/SlidingWindow.java
> +public class SlidingWindow {
Implement all problems in Sliding Window problems in Sliding Window Folder for **bonus score**

2023-01-10 11:02 UTC, 072arushi approved these changes
Approved

2023-01-10 11:23 UTC, zugzwang03 reviewed
Adding comment lines explaining your approach would have been better

2023-01-10 11:26 UTC, siddhi-244 requested changes
Can you remove those extra files committed which is the .vscode folder which is really not needed!

2023-01-11 13:59 UTC, Arun9739 requested changes
Remove the .vscode foder. It is not necessary for the code.

2023-02-12 08:36 UTC, mvpamansingh commented
@Kumar-laxmi @Arun9739 @siddhi-244 I have removed the vs folder, please check the pr

2023-02-14 02:43 UTC, siddhi-244 requested changes
Add some comments to explain the code

2023-02-14 16:00 UTC, Arun9739 approved these changes

2023-02-15 17:20 UTC, mvpamansingh commented
@siddhi-244 I have added comments ,please review it
@Kumar-laxmi changed the pr title please review it

2023-02-16 13:35 UTC, zugzwang03 approved these changes

2023-02-16 14:11 UTC, siddhi-244 approved these changes

2023-02-17 01:46 UTC, mvpamansingh commented
@Kumar-laxmi I have updated the pr title, please review it..

2023-02-20 01:28 UTC, Kumar-laxmi requested changes

2023-02-20 01:28 UTC, Kumar-laxmi commented on Java/Sliding Window/SlidingWindow.java
> +public class SlidingWindow {
@mvpamansingh Please implement all the problems of Sliding Window as mentioned in issue

2023-02-20 01:38 UTC, Kumar-laxmi approved these changes

2023-02-20 01:45 UTC, merged