Travelling Salesman Problem in C
Kumar-laxmi/Algorithms pull request #246
Opened 2023-01-07 15:36 UTC by papri24majumder

## 🛠️ Issue (Number)

Issue no #170 

## 👨‍💻 Changes proposed

Added traveling salesman problem in c language under dynamic programming

## ✔️ Check List (Check all the applicable boxes) 

- [✔️ ] My code follows the code style of this project.
- [ ✔️] This PR does not contain plagiarized content.
- [ ✔️] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers

## 📷 Screenshots
![output](https://user-images.githubusercontent.com/101787864/211158600-334f7815-6b6e-4d5a-a800-72fbcf558beb.jpg)

2023-01-10 11:21 UTC, zugzwang03 approved these changes

2023-01-10 11:21 UTC, zugzwang03 commented on README.md
> +
remove this change, as it is unnecessary

2023-01-10 11:26 UTC, siddhi-244 approved these changes
LGTM

2023-01-12 10:10 UTC, papri24majumder commented
@siddhi-244 can I make another issue or wait till this pr gets merged?

2023-01-12 12:56 UTC, zugzwang03 commented
> @siddhi-244 can I make another issue or wait till this pr gets merged?

You can make another issue

2023-01-12 14:12 UTC, papri24majumder commented
> 

ok thanks

2023-01-14 15:58 UTC, Kumar-laxmi requested changes
Remove this updation to README.md from this PR

2023-01-15 14:10 UTC, closed without merging