Added Beautiful string Program in C, C++, Java and Python
Kumar-laxmi/Algorithms pull request #297
Opened 2023-01-10 16:36 UTC by atul1510

## 🛠️ Issue #261 

## ✔️ Check List

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers
 Problem Statement: Atul has been given a binary string ‘STR’ containing either ‘0’ or ‘1’. A binary string is called beautiful if it contains alternating 0s and 1s.
For Example:‘0101’, ‘1010’, ‘101’, ‘010’ are beautiful strings.
He wants to make ‘STR’ beautiful by performing some operations on it. In one operation, Atul can convert ‘0’ into ‘1’ or vice versa.
Your task is to determine the minimum number of operations Atul should perform to make ‘STR’ beautiful.
## 📷 Screenshots

![Screenshot (116)](https://user-images.githubusercontent.com/97626275/211608943-5f069dc6-7c64-4508-98e7-3c600368dcf0.png)

2023-01-10 18:12 UTC, 072arushi requested changes
Please explain your approach

2023-01-11 13:23 UTC, zugzwang03 approved these changes

2023-01-11 14:20 UTC, Arun9739 approved these changes
Good contribution. Approved !

2023-01-11 14:28 UTC, 072arushi approved these changes

2023-01-11 15:45 UTC, merged