116 kruskal's algo
Kumar-laxmi/Algorithms pull request #323
Opened 2023-01-12 17:02 UTC by Piyush-onGIT

Fixed issue no #116 

## 👨‍💻 Changes proposed

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers

Added code for Kruskal's Algorithm in C++

## 📷 Screenshots
![Screenshot (8)](https://user-images.githubusercontent.com/60540783/212131989-717e763e-c448-4969-b3df-42afb60b10b6.png)

2023-01-13 01:17 UTC, siddhi-244 requested changes
Add some one line comments so that the approach is understood well .

2023-01-13 01:17 UTC, siddhi-244 commented on C++/Graphs/Kruskal_Algo.cpp
> +    u = findPar(u, parent);
Try to add a comment here for eg why we are finding out parents? How it would help ?

2023-01-13 13:56 UTC, zugzwang03 approved these changes

2023-01-13 14:02 UTC, Rishikavishnoi approved these changes

2023-01-14 17:29 UTC, Sanjanabharadwaj25 approved these changes

2023-02-28 06:37 UTC, Kumar-laxmi requested changes
Mention the issue number of ```Kosaraju_Algorithm.cpp``` and update the title accordingly

2023-03-04 08:31 UTC, Kumar-laxmi commented
@Piyush-onGIT Kindly do the required changes within a week or else this PR will be closed

2023-03-10 09:12 UTC, closed without merging