Max Area of Rectangle using Histogram by Stack
Kumar-laxmi/Algorithms pull request #381
Opened 2023-01-16 14:05 UTC by atul1510

## 🛠️ Issue #374 

## ✔️ Check List 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers

To determine the largest area in a given histogram by using stack.
INPUT: { 5,4,1,6,3,2,2}
OUTPUT: 8

## 📷 Screenshots
![Screenshot (130)](https://user-images.githubusercontent.com/97626275/212696540-7eb3f137-da14-48d4-802e-da8e5cb28bef.png)

2023-01-16 16:46 UTC, 072arushi approved these changes
Approved

2023-01-19 03:09 UTC, siddhi-244 requested changes
Update the pr title according to the algorithms you have added !

2023-01-19 13:57 UTC, 072arushi approved these changes

2023-01-20 16:08 UTC, Arun9739 approved these changes
@atul1510 Well done !
Approved !

2023-01-21 14:28 UTC, siddhi-244 approved these changes

2023-01-23 01:11 UTC, Kumar-laxmi approved these changes

2023-01-23 01:14 UTC, merged