Converting a Binary number to a Decimal number and a  Decimal number to Binary number in C
Kumar-laxmi/Algorithms pull request #400
Opened 2023-01-18 04:41 UTC by Abhilash1781

## 🛠️ Issue (270)

Issue no #270 

## 👨‍💻 Changes proposed
Added the required file in Maths folder . 
Updated README.md file .

## ✔️ Check List (Check all the applicable boxes) 

- [✔️ ] My code follows the code style of this project.
- [ ✔️] This PR does not contain plagiarized content.
- [ ✔️] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers
This C program can convert given (USER/EXPLICIT INPUT) Binary to decimal & given decimal to binary equivalent . 

## 📷 Screenshots
![d_b_b_d](https://user-images.githubusercontent.com/72621930/213085675-a6e48b15-6f79-4c72-b313-895562b0c673.png)

2023-01-18 04:43 UTC, Abhilash1781 commented
@zugzwang03 @072arushi

2023-01-18 13:25 UTC, Kumar-laxmi requested changes
Don't update the README.md

2023-01-18 14:33 UTC, zugzwang03 approved these changes

2023-01-18 15:09 UTC, Rishikavishnoi approved these changes

2023-01-18 15:12 UTC, Rancho2002 approved these changes

2023-01-19 01:32 UTC, Kumar-laxmi commented
Updation in **README.md** will cause merge conflict, so kindly remove its updation from this PR

2023-01-21 16:43 UTC, closed without merging