Bisection Algorithm Added
Kumar-laxmi/Algorithms pull request #443
Opened 2023-01-23 11:36 UTC by programmingninjas

## 🛠️ Issue (390)

Issue no #390 

## 👨‍💻 Changes proposed

Bisection method algorithm added in C, C++, Java and Python

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers

## 📷 Screenshots
C :
![image](https://user-images.githubusercontent.com/67486606/214029753-4cc732d5-103b-4b7d-919a-c017287ea6de.png)
C++ :
![image](https://user-images.githubusercontent.com/67486606/214029889-61c39e67-c877-4fca-be69-88d8c7844661.png)
Java :
![image](https://user-images.githubusercontent.com/67486606/214029988-5cea0e7c-2eb6-4b21-9f5a-a8fee7a00ef6.png)
Python :
![image](https://user-images.githubusercontent.com/67486606/214030066-894bfa2f-46fa-4ee7-acbf-7a64034e34f9.png)

2023-01-24 01:42 UTC, Kumar-laxmi requested changes
Don't update the **README.md**

2023-01-24 06:18 UTC, programmingninjas commented
Fixed the readme issue. Review now @Kumar-laxmi

2023-01-25 17:06 UTC, 072arushi approved these changes

2023-01-26 09:04 UTC, siddhi-244 approved these changes

2023-01-27 05:41 UTC, zugzwang03 approved these changes

2023-01-28 01:31 UTC, Kumar-laxmi approved these changes

2023-01-28 01:32 UTC, merged