KNN Algorithm in Python
Kumar-laxmi/Algorithms pull request #458
Opened 2023-01-24 13:28 UTC by Soumya-Kushwaha

## 🛠️ 444

Issue no #444

## 👨‍💻 Changes proposed

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers

## 📷 Screenshots

2023-01-25 01:49 UTC, Kumar-laxmi requested changes
@Soumya-Kushwaha You have to implement this algorithm from scratch and not using Library

2023-01-25 01:49 UTC, Kumar-laxmi commented
Please make required changes till then this PR is on ```Stand by```

2023-02-02 13:47 UTC, Kumar-laxmi commented
Kindly resolve the problems within 2 days or else the PR will be closed and marked ```Stale```

2023-02-02 18:29 UTC, 072arushi approved these changes

2023-02-03 04:11 UTC, closed without merging