LRU Cache Design
Kumar-laxmi/Algorithms pull request #490
Opened 2023-01-28 16:10 UTC by siddarth-ba-72

## 🛠️ Issue (#302 )

## 👨‍💻 Changes proposed
Implemented LRU Cache Design algorithm in all 4 languages

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers
    Problem Statement:-
Cache is the memory very close to CPU and has less access time. Cache is fast but also has less Space compared to RAM. Since it is small we need to have efficient utilization of small size memory. LRU(Least Recently Used) is one of the techniques for this purpose.
In LRU Cache we keep the recently accessed item least recently used item. This can be implemented using Doubly Linked List and Hash Set

    Algorithm:-
- Look for the page number in Set
- If found(page hit) then find the node with this page number and move it to the front of the linked list
- If not found(page miss) then:
    - Insert a new node with this page number at the front of the linked list
    - Insert an entry to the Set
    - If there are no empty frames left then remove the last node from the linked list
    - If there are empty frames left then increase the number of pages by 1

## 🕒 Time Complexity
- Searching, Adding, Removing an element from Hash table: O(1)
- Page Hit Condition: O(n)
- Page Miss Condition: O(1)
- Displaying Cache: O(n)

## 📷 Screenshots
These are the Screenshots of the output of the code.
This is the example of how the algorithm runs when we give different page numbers to the Cache

![op1](https://user-images.githubusercontent.com/84430963/215276420-b47c46be-e86f-49fe-bf0c-bc05b463858a.png)
![op2](https://user-images.githubusercontent.com/84430963/215276425-8cd43139-9933-4006-8cc5-13483311ed6a.png)

2023-01-29 06:19 UTC, zugzwang03 approved these changes

2023-01-29 14:56 UTC, Arun9739 requested changes
@siddarth-ba-72 Nice work!
But codefactor is showing some issues, plz look over there.

2023-01-30 03:52 UTC, siddarth-ba-72 commented
I have tried to fix the issues that were showing in codefactor

2023-01-30 07:00 UTC, zugzwang03 approved these changes

2023-01-31 16:40 UTC, Arun9739 approved these changes
Approved!

2023-02-01 01:15 UTC, Kumar-laxmi approved these changes

2023-02-01 01:19 UTC, merged