Order agnostic binary search in C++
Kumar-laxmi/Algorithms pull request #511
Opened 2023-01-31 13:33 UTC by VaibhavArora314

## 🛠️ Issue 348

Issue no #348 

## 👨‍💻 Changes proposed

Added algorithm of order agnostic binary search in C++

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers

## 📷 Screenshots
![image](https://user-images.githubusercontent.com/84830429/215774071-2f761a2a-c7d1-4863-af29-12a545e57399.png)
![image](https://user-images.githubusercontent.com/84830429/215774215-176e2763-156f-4bd1-89a0-5a058c94b7c4.png)

2023-02-01 09:42 UTC, 072arushi requested changes
Add time complexity and space complexity as well

2023-02-01 12:25 UTC, VaibhavArora314 commented
> Add time complexity and space complexity as well

Done, I have added it as comments in my code

2023-02-01 12:59 UTC, zugzwang03 approved these changes

2023-02-01 16:04 UTC, Arun9739 approved these changes
Nice !

2023-02-01 19:20 UTC, 072arushi approved these changes

2023-02-02 07:10 UTC, Rishikavishnoi approved these changes

2023-02-04 13:35 UTC, Kumar-laxmi approved these changes

2023-02-04 13:40 UTC, merged