Closures of a relation
Kumar-laxmi/Algorithms pull request #514
Opened 2023-02-01 05:59 UTC by VaibhavArora314

## 🛠️ Issue 498

Issue no #498

## 👨‍💻 Changes proposed

Added program to find closures of relation in C, C++, Java, and Python.

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers

## 📷 Screenshots
![image](https://user-images.githubusercontent.com/84830429/215963406-aa545a70-c2ab-492b-bcac-115323ffd04d.png)
![image](https://user-images.githubusercontent.com/84830429/215963564-e40a30da-2ea3-468a-b2d0-56473bd53c35.png)

2023-02-02 08:06 UTC, 072arushi requested changes
Add comments to explain your algorithm

2023-02-02 13:37 UTC, VaibhavArora314 commented
> Add comments to explain your algorithm

Done

2023-02-02 18:30 UTC, 072arushi approved these changes

2023-02-03 13:42 UTC, Rishikavishnoi approved these changes

2023-02-04 17:02 UTC, zugzwang03 approved these changes

2023-02-05 07:42 UTC, Arun9739 approved these changes

2023-02-06 03:45 UTC, merged