Added triplet algorithm in all four languages using sorting
Kumar-laxmi/Algorithms pull request #520
Opened 2023-02-01 21:01 UTC by atul1510

## 🛠️ Issue #482

## ✔️ Check List 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers

Problem Description :
Given an array and a value, find if there is a triplet in the array whose sum is equal to the given value. If there is such a triplet present in the array, then print the triplet and return true. Else return false.

EXAMPLES:
1] Input: array = { 7, 10, 6, 14, 4, 9 }, sum = 25;
Output: Triplet is 4, 7, 14
![Screenshot (157)](https://user-images.githubusercontent.com/97626275/216162309-43b27f27-f017-4387-8445-834a5d1e3243.png)

## 📷 Screenshots

2023-02-02 07:09 UTC, Rishikavishnoi approved these changes

2023-02-02 07:12 UTC, Rishikavishnoi reviewed
@atul1510 But take input from the user, instead of giving it directly in a program.

2023-02-02 08:04 UTC, 072arushi approved these changes

2023-02-02 16:42 UTC, zugzwang03 approved these changes

2023-02-03 04:33 UTC, Sanjanabharadwaj25 approved these changes

2023-02-05 07:35 UTC, Arun9739 requested changes
@atul1510 Take input from user, instead of giving it directly in program

2023-02-18 21:07 UTC, atul1510 commented
> @atul1510 Take input from user, instead of giving it directly in program

@Arun9739  I have completed all the requested changes. please review them.

2023-02-19 15:12 UTC, Arun9739 approved these changes

2023-02-22 01:34 UTC, Kumar-laxmi approved these changes

2023-02-22 01:35 UTC, merged