issue #376  in c
Kumar-laxmi/Algorithms pull request #532
Opened 2023-02-05 18:29 UTC by viveksondhiya

## 🛠️ Issue (Number)

Issue no #376 

## 👨‍💻 Changes proposed

## ✔️ Check List (Check all the applicable boxes) 

- [ ✔️] My code follows the code style of this project.
- [✔️ ] This PR does not contain plagiarized content.

## 📄 Note to reviewers

## 📷 Screenshots

2023-02-06 01:20 UTC, Kumar-laxmi requested changes
Give appropriate PR title

2023-02-06 06:38 UTC, viveksondhiya reviewed
corrections done

2023-02-06 08:04 UTC, zugzwang03 requested changes
add comments explaining approach

2023-02-06 08:08 UTC, viveksondhiya reviewed
Added the approach

2023-02-06 09:35 UTC, zugzwang03 approved these changes

2023-02-06 09:47 UTC, Rishikavishnoi approved these changes

2023-02-06 17:16 UTC, 072arushi approved these changes

2023-02-06 17:44 UTC, Arun9739 requested changes
@viveksondhiya Add screenshot of the output

2023-02-06 17:44 UTC, Arun9739 commented on C/Stack/nextgreaterelement.c
> +# Initialize the stack with a dummy element with a value of -1.
In C language, # will not be used for comments.
Plz put appropriate code.

2023-02-06 18:29 UTC, viveksondhiya reviewed
Changes done

2023-02-07 16:24 UTC, Arun9739 approved these changes

2023-02-12 06:27 UTC, closed without merging