Next greater Element using java
Kumar-laxmi/Algorithms pull request #549
Opened 2023-02-09 17:14 UTC by viveksondhiya

## 🛠️ Issue (Number)

Issue no #376 

## 👨‍💻 Changes proposed

## ✔️ Check List (Check all the applicable boxes) 

- [ ✔️] My code follows the code style of this project.
- [✔️ ] This PR does not contain plagiarized content.
- [ ✔️] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers

## 📷 Screenshots
![image](https://user-images.githubusercontent.com/98210740/217888031-2de6477d-8e47-4845-815a-c70a04670a7e.png)

2023-02-10 03:56 UTC, siddhi-244 approved these changes

2023-02-10 06:14 UTC, Rishikavishnoi approved these changes

2023-02-10 10:40 UTC, 072arushi approved these changes

2023-02-10 16:16 UTC, Arun9739 approved these changes

2023-02-12 06:09 UTC, Kumar-laxmi approved these changes

2023-02-12 06:12 UTC, Kumar-laxmi requested changes
Please include the C file in this PR, don't create a separate PR for C

2023-02-12 06:13 UTC, Kumar-laxmi commented
Please close the PR #532

2023-02-12 06:26 UTC, viveksondhiya reviewed
Added c file in this pr and close the pr #532

2023-02-12 06:31 UTC, Kumar-laxmi approved these changes

2023-02-12 06:34 UTC, merged