Roman to decimal
Kumar-laxmi/Algorithms pull request #569
Opened 2023-02-15 11:05 UTC by atul1510

## 🛠️ Issue #566 

## 👨‍💻 Changes proposed

## ✔️ Check List 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers

Problem Statement
Given a Roman numeral, the task is to convert it into its decimal equivalent.

Approach
The approach used to solve this problem is to iterate over each character in the input Roman numeral string in reverse order. If the value of the current symbol is greater than or equal to the value of the previous symbol, it is added to the result. If the value of the current symbol is less than the value of the previous symbol, it is subtracted from the result.

Example
1)
Input: "XXI"
Output: 21
2)
Input: "MCMXCIV"
Output: 1994

## 📷 Screenshots

![Screenshot (183)](https://user-images.githubusercontent.com/97626275/219010611-7c9f3c4b-03b1-4277-9767-4546bc2fb66a.png)

2023-02-16 03:03 UTC, Kumar-laxmi requested changes
Please include the issue number of ```Symmetric Trees``` in PR description and change the file name ```Node.java``` to ```Symmetric_Tree.java```

2023-02-16 11:53 UTC, siddhi-244 approved these changes

2023-02-16 13:36 UTC, zugzwang03 approved these changes

2023-02-17 07:44 UTC, Rishikavishnoi approved these changes

2023-02-18 12:58 UTC, atul1510 commented
> Please include the issue number of `Symmetric Trees` in PR description and change the file name `Node.java` to `Symmetric_Tree.java`

Done with all the changes. Kindly review it.

2023-02-18 13:04 UTC, Arun9739 approved these changes

2023-02-18 19:34 UTC, Sanjanabharadwaj25 approved these changes

2023-02-19 15:25 UTC, Kumar-laxmi approved these changes

2023-02-19 15:26 UTC, merged