Hill Cipher Implementation in C++ & Python
Kumar-laxmi/Algorithms pull request #600
Opened 2023-02-25 11:29 UTC by Paritosh-J

## 🛠️ Issue (Number)

Issue no #580

## ✔️ Check List 

- My code follows the code style of this project.
- This PR does not contain plagiarized content.
- The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers

### Definition

👉 In classical cryptography, the Hill cipher is a polygraphic substitution cipher based on linear algebra. 

👉 Invented by Lester S. Hill in 1929, it was the first polygraphic cipher in which it was practical to operate on more than three symbols at once.

### Steps

⇒ Generate a cipher key 2x2 matrix by replacing characters with numerical values.
⇒ Generate a vector of 2x1 matrices with numeric codes of plain text characters.
⇒ Multiply the key mtx. with each 2x1 matrix in plain text matrix vector & mod the result with 26, to obtain the cipher text numeric values.
⇒ Convert these numeric values back to alphabetic characters to obtain the cipher text.

2023-02-25 13:41 UTC, Arun9739 requested changes
Add a output screenshot

2023-02-27 15:14 UTC, Paritosh-J commented
> Add a output screenshot

@Arun9739 uploaded the screenshot.

2023-02-27 16:48 UTC, zugzwang03 approved these changes

2023-02-28 07:46 UTC, 072arushi approved these changes

2023-02-28 14:01 UTC, Arun9739 approved these changes

2023-02-28 16:30 UTC, Kumar-laxmi approved these changes

2023-02-28 16:32 UTC, merged