Homophonic substitution in C,C++,java and python
Kumar-laxmi/Algorithms pull request #612
Opened 2023-02-28 19:22 UTC by MrKoshens

## 🛠️ Issue (#592 )

Issue no #592 

## 👨‍💻 Changes proposed

Added complete code for homophonic substitution in python, C, C++, and java

## ✔️ Check List (Check all the applicable boxes) 

- [* ] My code follows the code style of this project.
- [* ] This PR does not contain plagiarized content.
- [* ] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers

## 📷 Screenshots
![2023-02-28_23-10](https://user-images.githubusercontent.com/74851124/221956406-068ec276-f0d9-459a-9923-30342aca6b55.jpg)

2023-03-01 02:54 UTC, siddhi-244 requested changes
I can see SHA files too ! Please create different prs for different issues ! Try to use different branches

2023-03-01 16:00 UTC, 072arushi approved these changes

2023-03-01 16:03 UTC, MrKoshens commented
> I can see SHA files too ! Please create different prs for different issues ! Try to use different branches

I have deleted the SHA256 files. please check now

2023-03-02 18:00 UTC, Arun9739 approved these changes

2023-03-04 16:46 UTC, Rancho2002 approved these changes

2023-03-05 06:01 UTC, Kumar-laxmi approved these changes

2023-03-05 06:02 UTC, merged