Added detect loop in a linked list in C++.
Kumar-laxmi/Algorithms pull request #635
Opened 2023-03-10 13:55 UTC by sumitkr2000

## 🛠️ Issue (Number)

Issue no #122 

## 👨‍💻 Changes proposed

Hey, @Kumar-laxmi I have added the code to detect a loop in a linked list in C++. Please review my pr and merge it. Thank you!

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers

## 📷 Screenshots
![Screenshot (688)](https://user-images.githubusercontent.com/100675296/224333860-fffc0b09-bb5d-4978-8656-90e95667f8f0.png)

2023-03-11 16:24 UTC, siddhi-244 approved these changes

2023-03-12 06:55 UTC, 072arushi requested changes
add comment to explain your approach

2023-03-12 11:23 UTC, sumitkr2000 commented
@072arushi It has been added, see carefully.

2023-03-12 15:46 UTC, 072arushi approved these changes

2023-03-14 04:59 UTC, sumitkr2000 commented
@zugzwang03 Approve my pull request today is the last day.

2023-03-14 10:02 UTC, merged