Tower of Hanoi Code Added in C and C++
Kumar-laxmi/Algorithms pull request #714
Opened 2023-05-30 19:27 UTC by gitsofaryan

![TowerOfHanoi IN C++](https://github.com/Kumar-laxmi/Algorithms/assets/117700812/a6313a23-e69e-47d6-baaf-c5e3970e59b5)
![Screenshot 2023-05-31 214150](https://github.com/Kumar-laxmi/Algorithms/assets/117700812/2ee6228d-c4c6-4c15-913c-89602e0c9f7c)

## 🛠️ Issue (Number)

Issue no #677 

## 👨‍💻 Changes proposed

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers

## 📷 Screenshots

2023-05-31 05:39 UTC, Kumar-laxmi commented
There is no issue number mentioned

2023-05-31 09:03 UTC, gitsofaryan commented
updated...! sorry for the error...

2023-05-31 16:18 UTC, gitsofaryan commented
Done.

2023-06-02 01:06 UTC, siddhi-244 approved these changes

2023-06-02 11:26 UTC, zugzwang03 approved these changes

2023-06-02 13:06 UTC, Arun9739 approved these changes

2023-06-03 01:07 UTC, Kumar-laxmi requested changes

2023-06-03 01:07 UTC, Kumar-laxmi commented on C++/TowerOfHanoi/README.md
> +Explanation:
Please don't create separate folder for this algorithm instead create ```<language_file>/Recursion/<program_file>```.
Ex: C++/Recursion/TowerOfHanoi.cpp

And you can add README.md content as comment inside your program file

2023-06-03 01:07 UTC, Kumar-laxmi commented on C/TowerOfHanoi/README.md
> +Explanation:
Please don't create separate folder for this algorithm instead create ```<language_file>/Recursion/<program_file>```.
Ex: C/Recursion/TowerOfHanoi.c

And you can add README.md content as comment inside your program file

2023-06-04 05:02 UTC, Kumar-laxmi commented
@gitsofaryan Please do the required changes within a week or else PR would be marked ```Stale```

2023-06-08 06:05 UTC, zugzwang03 requested changes
remove readme files

2023-06-08 12:13 UTC, gitsofaryan commented
Already deleted.

2023-06-08 14:59 UTC, Kumar-laxmi requested changes
Please place the program files in both languages inside the Recursion folder, no need to create additional folder

2023-06-09 06:19 UTC, gitsofaryan commented
please i request to re-check my PR.

2023-06-09 14:30 UTC, zugzwang03 approved these changes

2023-06-11 05:13 UTC, zugzwang03 approved these changes

2023-06-12 03:08 UTC, Kumar-laxmi approved these changes

2023-06-12 03:08 UTC, merged