Fractional knapsack problem
Kumar-laxmi/Algorithms pull request #741
Opened 2023-05-31 16:31 UTC by manu31shukla

## Description
This PR adds the implementation of the fractional knapsack algorithm to the `Algorithms` repository. The fractional knapsack algorithm is used to solve the fractional knapsack problem, which involves selecting items with maximum total value while respecting a weight constraint.

## Changes Made
- Added a new file `Fractional Knapsack `folder  to the 'Dynamic Programming folder of `Algorithms` directory for C++, Java and Python language, containing the implementation of the fractional knapsack algorithm.
- Added comments to explain each step of the algorithm and provide insights into the problem it solves.
- Added README file for better understanding.

## Testing
- Ran the algorithm on various input scenarios and compared the results with expected outcomes.
- All test cases passed successfully, demonstrating the correctness of the implementation.

## Related Issue
issue no. #688 

## Checklist
- [x] The code follows the coding style guidelines of the repository.
- [x] The code is well-documented with comments to improve readability.
- [x] Tests have been added to ensure the correctness of the algorithm.
- [x] The code has been tested locally and runs without any errors.
- [x] All existing tests pass successfully.
- [x] The PR has a descriptive title and provides sufficient information.

Please review this PR and let me know if any further modifications or changes are required. Thank you!

2023-06-01 09:56 UTC, Kumar-laxmi commented
Kindly sort **CodeFactor** issues

2023-06-02 03:46 UTC, Kumar-laxmi commented
@manu31shukla Kindly include the Screen-shot of your implementation

2023-06-02 11:23 UTC, zugzwang03 approved these changes

2023-06-09 17:59 UTC, Arun9739 requested changes
@manu31shukla  Add output screenshots

2023-06-10 05:42 UTC, 072arushi approved these changes

2023-06-16 03:18 UTC, closed without merging