Adding Cyclic Sort Algo In Java
Kumar-laxmi/Algorithms pull request #77
Opened 2023-01-01 14:35 UTC by VishalS-HK

Cyclic sort in Java

2023-01-01 14:41 UTC, Kumar-laxmi requested changes
Kindly give some description and your approach in the issue as well as PR

2023-01-01 14:46 UTC, VishalS-HK commented
Cylic Sort is a sorting algorithm ideally used if the question
reads "given range of numbers from 0 to N or 1 to N"

Approach used :
Check if the number is in the correct index, if not swap, and then continue iterating.

2023-01-01 14:47 UTC, VishalS-HK commented
Cylic Sort is a sorting algorithm ideally used if the question
reads "given range of numbers from 0 to N or 1 to N"

Approach used :
Check if the number is in the correct index, if not swap, and then continue iterating.

2023-01-01 14:48 UTC, VishalS-HK commented
Is that fine? @Kumar-laxmi

2023-01-01 15:02 UTC, VishalS-HK commented
Or should I create a new pr?

2023-01-01 15:20 UTC, Kumar-laxmi requested changes
Update the repository README.md

2023-01-01 15:38 UTC, VishalS-HK commented
Done could you check

2023-01-02 01:21 UTC, Kumar-laxmi requested changes

2023-01-02 01:21 UTC, Kumar-laxmi commented on README.md
> +| 16.  | Cyclic Sort | [Java](https://github.com/Kumar-laxmi/Algorithms/tree/main/Java/Sorting) | Sorting |
Place Cyclic Sort between Bubble and Heap Sort

2023-01-02 02:30 UTC, closed without merging

2023-01-02 02:34 UTC, Kumar-laxmi commented
@VishalS-HK Why did you close this PR??