Permutations algo added in c, c++, java and python
Kumar-laxmi/Algorithms pull request #816
Opened 2023-06-01 10:50 UTC by Jiggy9

## 🛠️ Issue (Number)

Issue no #716

## 👨‍💻 Changes proposed
Added Permutations algo in Recursion folder in c, c++, python and java languages.

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots
<img width="762" alt="c" src="https://github.com/Kumar-laxmi/Algorithms/assets/112299754/f1b81637-38b2-47b5-a566-5bb868ea4386">

<img width="726" alt="c++" src="https://github.com/Kumar-laxmi/Algorithms/assets/112299754/8b6830bc-f10a-46a0-aa4d-4e372984e511">

<img width="727" alt="java" src="https://github.com/Kumar-laxmi/Algorithms/assets/112299754/14234215-bec1-4ebf-b8e6-31d3392b4a41">

<img width="718" alt="python" src="https://github.com/Kumar-laxmi/Algorithms/assets/112299754/07d7b90f-45b5-4fec-b552-a243e3622f98">

2023-06-01 14:04 UTC, zugzwang03 approved these changes

2023-06-02 11:24 UTC, zugzwang03 approved these changes

2023-06-02 13:04 UTC, Arun9739 requested changes
@Jiggy9 Add output screenshots

2023-06-04 15:41 UTC, Arun9739 approved these changes

2023-06-05 11:36 UTC, Kumar-laxmi approved these changes

2023-06-05 11:36 UTC, merged