I have added the program for the removal of cycle in linked list in c…
Kumar-laxmi/Algorithms pull request #890
Opened 2023-06-02 08:48 UTC by singhapeksha

…, c++, python and JAVA

## 🛠️ Issue (759)

Issue no #759 

## 👨‍💻 Changes proposed

Changes proposed in PR:
Added code for the removal of linked list cycle "RemoveCycle"
in Python, C++, C, JAVA
## ✔️ Check List (Check all the applicable boxes) 

- [✅ ] My code follows the code style of this project.
- [✅ ] This PR does not contain plagiarized content.
- [✅ ] The title of my pull request is a short description of the requested changes.

## 📄 I have added the code for Removal of linked list cycle in C, C++,Python, Java

2023-06-09 17:39 UTC, singhapeksha commented
@Kumar-laxmi Please look into my code.

2023-06-13 05:36 UTC, Kumar-laxmi requested changes
Kindly give same name to all program files

2023-06-13 11:21 UTC, zugzwang03 approved these changes

2023-06-16 06:55 UTC, Arun9739 requested changes
@singhapeksha Add output screenshot

2023-06-16 08:34 UTC, 072arushi approved these changes

2023-06-21 05:55 UTC, zugzwang03 approved these changes

2023-07-07 04:13 UTC, closed without merging