ADD: Flood Fill Algorithm in C and C++ under Recursion.
Kumar-laxmi/Algorithms pull request #897
Opened 2023-06-02 10:38 UTC by XRegiGigaSX

🛠️ Issue #808 

👨‍💻 Changes proposed
I have added code for Flood Fill Algorithm in C and C++.

✔️ Check List (Check all the applicable boxes) 

- [ ✔️] My code follows the code style of this project.
- [ ✔️] This PR does not contain plagiarized content.
- [ ✔️] The title of my pull request is a short description of the requested changes.

📄 Note to reviewers
The code added for C is has hard coded input, whereas code added for C++ accepts user input. I have done for simplicity of the users so that they can test out the algorithm with their own testcases if they please to do so.

2023-06-03 10:26 UTC, Kumar-laxmi requested changes

2023-06-03 10:26 UTC, Kumar-laxmi commented on C++/Recursion/README.md
> +# Recursion
Remove this README.md file

2023-06-03 11:34 UTC, XRegiGigaSX commented on C++/Recursion/README.md
> +# Recursion
I have deleted the README.md file

2023-06-04 05:00 UTC, zugzwang03 approved these changes

2023-06-04 15:54 UTC, Arun9739 approved these changes

2023-06-20 14:52 UTC, Kumar-laxmi commented
@XRegiGigaSX Resolve the Merge conflict

2024-08-04 16:44 UTC, closed without merging