Added C,C++,Java & Python Code for Manacher's Algorithm
Kumar-laxmi/Algorithms pull request #908
Opened 2023-06-02 13:55 UTC by rituraj314

## 🛠️ Issue (Number)

Issue no #833

## 👨‍💻 Changes proposed

## ✔️ Check List (Check all the applicable boxes) 

- [ ✔️] My code follows the code style of this project.
- [ ✔️] This PR does not contain plagiarized content.
- [ ✔️] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers

Added C,C++,Java & Python code for Manacher's Algorithm under string file. All files are checked and giving the correct
output as expected.Kindly review the PR and merge it. 

## 📷 Screenshots
![Screenshot 2023-06-02 183827](https://github.com/Kumar-laxmi/Algorithms/assets/96370518/a25604d4-b70f-402c-92b8-1aeaafd4e8d2)
![Screenshot 2023-06-02 191256](https://github.com/Kumar-laxmi/Algorithms/assets/96370518/78e53889-cf70-4ced-896a-0793cf14e233)
![Screenshot 2023-06-02 191342](https://github.com/Kumar-laxmi/Algorithms/assets/96370518/cfd63db9-1f8e-45e0-b3ba-180780ff0907)
![Screenshot 2023-06-02 191418](https://github.com/Kumar-laxmi/Algorithms/assets/96370518/eb84c2fe-102e-4619-8548-2d3f9ec8a7fa)
![Screenshot 2023-06-02 191516](https://github.com/Kumar-laxmi/Algorithms/assets/96370518/915e3173-7d56-4f55-9a28-89d9dcf6f382)
![Screenshot 2023-06-02 191217](https://github.com/Kumar-laxmi/Algorithms/assets/96370518/92d07e1a-6d5b-4d84-844c-b2051cd52952)

2023-06-03 05:48 UTC, harshit7045 commented
Hello,

My name is Harshit Mishra, and I am a student at IIIT Una. I possess a strong understanding of data structures and algorithms and have the ability to write optimized code with explanatory comments. I kindly request to be assigned this issue.

2023-06-04 04:58 UTC, zugzwang03 approved these changes

2023-06-04 15:54 UTC, Arun9739 approved these changes

2023-06-11 04:00 UTC, Kumar-laxmi requested changes
Kindly resolve your CodeFactor issues

2023-06-20 14:49 UTC, Kumar-laxmi approved these changes

2023-06-23 05:33 UTC, merged