N-Queens Problem in c ,c++, JAVA and python
Kumar-laxmi/Algorithms pull request #920
Opened 2023-06-02 18:21 UTC by ShubhaSwarup

Added code for solving N-Queens Problem in c ,c++, JAVA and python

#760 

Issue no #760 

## 👨‍💻 Changes proposed

## ✔️ Check List (Check all the applicable boxes) 

- [✅] My code follows the code style of this project.
- [✅] This PR does not contain plagiarized content.
- [✅] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers

## 📷 Screenshots
<img width="630" alt="Screenshot 2023-06-02 at 11 28 55 PM" src="https://github.com/Kumar-laxmi/Algorithms/assets/112583158/f98c57bb-5995-4537-bee3-d4fd9b921b42">

2023-06-03 01:36 UTC, Kumar-laxmi requested changes
Remove these files also: ```C++/Backtracking/N_Queen``` & ```C++/Backtracking/N_Queen.dSYM/Contents/Resources/DWARF/N_Queen```

2023-06-03 01:36 UTC, Kumar-laxmi commented on .vscode/tasks.json
> +{
Kindly remove this file ```.vscode/tasks.json```

2023-06-03 01:36 UTC, Kumar-laxmi commented on C++/Backtracking/N_Queen.dSYM/Contents/Info.plist
> +<?xml version="1.0" encoding="UTF-8"?>
Kindly remove this file ```C++/Backtracking/N_Queen.dSYM/Contents/Info.plist```

2023-06-03 06:27 UTC, ShubhaSwarup commented on C++/Backtracking/N_Queen.dSYM/Contents/Info.plist
> +<?xml version="1.0" encoding="UTF-8"?>
> Kindly remove this file `C++/Backtracking/N_Queen.dSYM/Contents/Info.plist`

okay i will remove these files

2023-06-03 06:49 UTC, ShubhaSwarup commented on C++/Backtracking/N_Queen.dSYM/Contents/Info.plist
> +<?xml version="1.0" encoding="UTF-8"?>
Removed. Please check again

2023-06-04 04:59 UTC, zugzwang03 approved these changes

2023-06-04 05:03 UTC, Kumar-laxmi approved these changes

2023-06-04 05:04 UTC, Kumar-laxmi requested changes
Please share the screen shot of your output and not the code

2023-06-04 10:24 UTC, ShubhaSwarup commented
> Please share the screen shot of your output and not the code in the PR description

Done

2023-06-09 13:59 UTC, Kumar-laxmi requested changes
Place this program in ```Divide and Conquer```

2023-06-09 17:34 UTC, ShubhaSwarup commented
> Place this program in `Divide and Conquer`

Done. Please check.

2023-06-11 03:53 UTC, Kumar-laxmi approved these changes

2023-06-11 03:54 UTC, Kumar-laxmi requested changes
Kindly put the screen shot of actual output in the PR description

2023-06-11 17:11 UTC, 072arushi approved these changes

2023-06-13 05:41 UTC, Kumar-laxmi requested changes
- The screen shots of Java & Python programs are missing
- You can give same name to all program files

2023-06-14 14:53 UTC, ShubhaSwarup commented
> * The screen shots of Java & Python programs are missing
> * You can give same name to all program files

Done.Please check.

2023-06-15 04:57 UTC, zugzwang03 requested changes

2023-06-15 04:57 UTC, zugzwang03 commented on C++/Divide-and-Conquer/N_Queen
remove this file

2023-06-15 04:57 UTC, zugzwang03 commented on C/Divide-and-Conquer/N_Queen
remove this file

2023-06-15 04:57 UTC, zugzwang03 commented on C/Divide-and-Conquer/N_Queen.dSYM/Contents/Resources/DWARF/N_Queen
remove this file

2023-06-15 09:17 UTC, ShubhaSwarup commented on C/Divide-and-Conquer/N_Queen.dSYM/Contents/Resources/DWARF/N_Queen
> remove this file

done.please check

2023-06-15 10:32 UTC, Kumar-laxmi requested changes
Remove: ```.vscode/tasks.json```

2023-06-16 04:33 UTC, zugzwang03 approved these changes

2023-06-19 10:58 UTC, merged