Added reverse linked list in group of K problem in C, Cpp, Python and…
Kumar-laxmi/Algorithms pull request #965
Opened 2023-06-03 13:12 UTC by pearlrathour

Closes #712

## 🛠️ Issue (Number)

Issue no #712 

## 👨‍💻 Changes proposed

## ✔️ Check List (Check all the applicable boxes) 

- [ x] My code follows the code style of this project.
- [ x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots

Cpp-
![image](https://github.com/Kumar-laxmi/Algorithms/assets/99817664/8bd54c6a-603e-45fc-ae5b-eb5ba18cbca9)

C-
![image](https://github.com/Kumar-laxmi/Algorithms/assets/99817664/a1815116-322d-43e0-b1ac-7ff0255a5fd0)

Java-
![image](https://github.com/Kumar-laxmi/Algorithms/assets/99817664/9030f118-7e5f-461d-9226-d252896aa338)

Python-
![image](https://github.com/Kumar-laxmi/Algorithms/assets/99817664/14b3a572-8ebd-4812-8282-3b6564fbc0e2)

2023-06-04 07:28 UTC, zugzwang03 approved these changes

2023-06-05 14:53 UTC, Arun9739 requested changes
@pearlrathour Add output screenshot, not the code.

2023-06-10 05:37 UTC, 072arushi approved these changes

2023-06-11 06:30 UTC, Arun9739 approved these changes

2023-06-12 03:15 UTC, Kumar-laxmi approved these changes

2023-06-12 03:17 UTC, merged