Added shell sort algorithm in C++,C , Java, Python
Kumar-laxmi/Algorithms pull request #969
Opened 2023-06-03 16:32 UTC by ANI2707

## 🛠️ Issue (Number)

Issue no #720

## 👨‍💻 Changes proposed

## ✔️ Check List (Check all the applicable boxes) 

- [X] My code follows the code style of this project.
- [X] This PR does not contain plagiarized content.
- [X] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers

## 📷 Screenshots

2023-06-04 05:01 UTC, zugzwang03 approved these changes

2023-06-04 15:56 UTC, Arun9739 approved these changes

2023-06-05 10:15 UTC, Kumar-laxmi requested changes
Please add the screen shot of your output

2023-06-06 01:11 UTC, Kumar-laxmi approved these changes

2023-06-06 01:13 UTC, merged