Tarjan's
Kumar-laxmi/Algorithms pull request #981
Opened 2023-06-04 03:44 UTC by weirdoo009

## 🛠️ Issue (Number)
Issue no #774 

## 👨‍💻 Changes proposed
Added Tarjan's Algorithm into C, Python & Java as the code was already present in C++.

## List all the proposed changes in your PR 

 Added the Algorithm in C language with detailed explanation
 Added the Algorithm in Java language with detailed explanation
 Added the Algorithm in Python language with  detailed explanation

## ✔️ Check List (Check all the applicable boxes) 

- [✔️] My code follows the code style of this project.
- [✔️] This PR does not contain plagiarized content.
- [✔️] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers

## 📷 Screenshots

2023-06-04 07:28 UTC, zugzwang03 approved these changes

2023-06-05 10:14 UTC, Kumar-laxmi requested changes
Please add the screen shot of your output

2023-06-06 04:28 UTC, weirdoo009 commented
@Kumar-laxmi I have uploaded the screenshots

2023-06-08 14:51 UTC, Kumar-laxmi approved these changes

2023-06-08 14:51 UTC, merged