Added fibonacci search in c++ , c , java ,python
Kumar-laxmi/Algorithms pull request #983
Opened 2023-06-04 05:05 UTC by ANI2707

## 🛠️ Issue (Number)

Issue no #690

## 👨‍💻 Changes proposed

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers

## 📷 Screenshots

2023-06-04 05:07 UTC, Kumar-laxmi requested changes
Please share the screen shot of your output

2023-06-04 07:31 UTC, zugzwang03 approved these changes

2023-06-05 14:57 UTC, Arun9739 approved these changes

2023-06-06 01:05 UTC, Kumar-laxmi approved these changes

2023-06-06 01:07 UTC, merged